(function(){'use strict';
const KEY='hh-daily-life-v1',names=['budget','reminders','grocery','meals','jobs','family','events','requests'];
let data={};let storageOK=true;try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');names.forEach(k=>data[k]=Array.isArray(raw[k])?raw[k].filter(x=>x&&typeof x==='object'&&typeof x.id==='string'):[]);}catch{names.forEach(k=>data[k]=[]);storageOK=false;}
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),today=()=>new Date().toLocaleDateString('en-CA');
function E(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function message(t){$('status').textContent=t;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));}catch{storageOK=false;message('Storage unavailable or full. Download your entries before closing this page.');}}
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type:type||'text/plain;charset=utf-8'}));const a=E('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);message('Download prepared. Keep it somewhere private.');}
function button(text,fn,parent){const b=E('button',text);b.type='button';b.addEventListener('click',fn);parent.append(b);return b;}
function link(text,url,parent){const a=E('a',text);a.href=url;a.target='_blank';a.rel='noopener';parent.append(a);return a;}
function tip(text,parent=body){parent.append(E('p',text,'tip'));}
const tools=[['budget','Household budget','Track monthly income and expenses. Enter all amounts as monthly USD estimates.'],['reminders','Bills & reminders','Keep due dates together and export reminders to your calendar app.'],['grocery','Groceries & meals','Build a shopping list and plan meals for the week.'],['help','Local help finder','Find trusted starting points for food, housing and other support.'],['phrases','Amharic–English phrases','Practice everyday phrases for school, work and appointments.'],['jobs','Job application tracker','Track applications, interview dates and next steps.'],['family','Family & school organizer','Keep homework, activities and household tasks in one place.'],['scam','Scam awareness helper','Check warning signs before acting on an unexpected message.'],['events','Community calendar','Save events and browse current community event sources.'],['requests','Service request board','Organize service request drafts and find providers in the directory.']];
let current='budget',body=$('toolBody');
function show(key,focus=false){if(!tools.some(t=>t[0]===key))key='budget';current=key;const t=tools.find(t=>t[0]===key);$('toolTitle').textContent=t[1];$('toolDescription').textContent=t[2];body.replaceChildren();document.querySelectorAll('#tools button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.key===key)));renderers[key]();history.replaceState(null,'','#'+key);if(focus)$('workspace').focus();}
tools.forEach(t=>{const b=button(t[1],()=>show(t[0],true),$('tools'));b.dataset.key=t[0];b.setAttribute('aria-controls','workspace');});
function field(form,s){const label=E('label',s.label);const input=E(s.options?'select':s.type==='textarea'?'textarea':'input');input.name=s.name;if(s.options)s.options.forEach(v=>{const o=E('option',v);o.value=v;input.append(o);});else input.type=s.type||'text';input.required=!!s.required;if(input.type==='number'){input.min='0';input.max='10000000';input.step='0.01';}if(input.type==='text'||input.tagName==='TEXTAREA')input.maxLength=500;label.append(input);form.append(label);return input;}
function formFor(key,specs,submit='Add entry'){const form=E('form');specs.forEach(s=>field(form,s));const b=E('button',submit);b.type='submit';form.append(b);form.addEventListener('submit',ev=>{ev.preventDefault();if(!form.reportValidity())return;const record=Object.fromEntries(new FormData(form));for(const s of specs)if(s.type==='number')record[s.name]=Number(record[s.name]);record.id=crypto.randomUUID();data[key].push(record);save();show(current);message('Entry saved'+(storageOK?' on this device.': ' for this visit only.'));});body.append(form);}
function list(key,draw){const wrap=E('div',undefined,'items');if(!data[key].length)wrap.append(E('p','No entries yet. Add your first one above.'));data[key].forEach(r=>{const card=E('article',undefined,'item');draw(r,card);const actions=E('div',undefined,'actions');button('Delete',()=>{data[key]=data[key].filter(x=>x.id!==r.id);save();show(current);message('Entry deleted.');},actions);card.append(actions);wrap.append(card);});body.append(wrap);return wrap;}
function dateText(date){return date?new Date(date+'T12:00:00').toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'No date set';}
function icsEscape(s){return String(s||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');}
function calendar(records){const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Habesha Hub//Daily Life//EN','CALSCALE:GREGORIAN'];records.filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date||'')).forEach(r=>{const next=new Date(r.date+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+1);lines.push('BEGIN:VEVENT','UID:'+r.id+'@habesha-hub','DTSTAMP:'+stamp,'DTSTART;VALUE=DATE:'+r.date.replace(/-/g,''),'DTEND;VALUE=DATE:'+next.toISOString().slice(0,10).replace(/-/g,''),'SUMMARY:'+icsEscape(r.title),'DESCRIPTION:'+icsEscape(r.notes||r.location||''),'BEGIN:VALARM','TRIGGER:-P1D','ACTION:DISPLAY','DESCRIPTION:Habesha Hub reminder','END:VALARM','END:VEVENT');});lines.push('END:VCALENDAR');return lines.join('\r\n')+'\r\n';}
function calendarButton(key){button('Download calendar (.ics)',()=>{if(!data[key].some(r=>r.date)){message('Add an entry with a date first.');return;}download('habesha-'+key+'.ics',calendar(data[key]),'text/calendar;charset=utf-8');},body);tip('Import the downloaded file into Google Calendar, Apple Calendar or Outlook. Entries are all-day; set appointment times in your calendar app. Notifications depend on that app’s settings. Habesha Hub does not send email or background alerts.');}
const title={name:'title',label:'Title',required:true};const date={name:'date',label:'Date',type:'date',required:true};const notes={name:'notes',label:'Notes (avoid sensitive details)',type:'textarea'};
const renderers={
budget(){formFor('budget',[{name:'month',label:'Budget month',type:'month',required:true},{name:'kind',label:'Type',options:['Income','Expense']},title,{name:'amount',label:'Monthly amount (USD)',type:'number',required:true}]);const filter=E('label','View month');const input=E('input');input.type='month';input.value=new Date().toISOString().slice(0,7);filter.append(input);body.append(filter);const result=E('div');body.append(result);function render(){result.replaceChildren();const rows=data.budget.filter(r=>r.month===input.value);const income=rows.filter(r=>r.kind==='Income').reduce((n,r)=>n+Number(r.amount||0),0),expense=rows.filter(r=>r.kind==='Expense').reduce((n,r)=>n+Number(r.amount||0),0);const m=E('div',undefined,'metrics');[['Income',income],['Expenses',expense],['Remaining',income-expense]].forEach(([label,v])=>{const card=E('div',label,'metric');card.append(E('strong',money(v)));m.append(card);});result.append(m);rows.forEach(r=>{const row=E('div',r.title+' · '+r.kind+' · '+money(r.amount),'item');button('Delete',()=>{data.budget=data.budget.filter(x=>x.id!==r.id);save();render();},row);result.append(row);});if(!rows.length)result.append(E('p','No budget entries for this month.'));}input.addEventListener('change',render);render();},
reminders(){formFor('reminders',[title,date,{name:'amount',label:'Amount due (USD, optional)',type:'number'},notes]);calendarButton('reminders');list('reminders',(r,c)=>{c.append(E('h3',r.title),E('p',dateText(r.date)+(r.date<today()&&!r.done?' · Past due date':'')),E('p',r.notes||''));button(r.done?'Mark unfinished':'Mark complete',()=>{r.done=!r.done;save();show(current);},c);if(r.done)c.classList.add('completed');});},
grocery(){formFor('grocery',[title,{name:'quantity',label:'Quantity',required:true},{name:'amount',label:'Estimated total cost (USD)',type:'number',required:true}],'Add shopping item');const total=data.grocery.filter(r=>!r.done).reduce((n,r)=>n+Number(r.amount||0),0);body.append(E('h3','Remaining shopping estimate: '+money(total)));list('grocery',(r,c)=>{c.append(E('h3',r.title),E('p',r.quantity+' · '+money(r.amount)));button(r.done?'Put back on list':'Mark purchased',()=>{r.done=!r.done;save();show(current);},c);if(r.done)c.classList.add('completed');});body.append(E('h3','Weekly meal plan'));tip('Ideas: lentil stew (misir wot), shiro with injera, vegetable stew, rice or pasta. Adjust ingredients for allergies and household preferences.');formFor('meals',[{name:'day',label:'Day',options:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']},{name:'title',label:'Meal',required:true},{name:'notes',label:'Ingredients to buy',type:'textarea'}],'Add meal');list('meals',(r,c)=>c.append(E('h3',r.day+' · '+r.title),E('p',r.notes)));},
help(){tip('For immediate danger, call 911. These links are resource starting points, not eligibility decisions or promises of assistance.');const label=E('label','ZIP code');const zip=E('input');zip.inputMode='numeric';zip.pattern='[0-9]{5}';zip.maxLength=5;label.append(zip);body.append(label);button('Find help near this ZIP',()=>{if(!/^\d{5}$/.test(zip.value)){message('Enter a five-digit ZIP code.');return;}const p=E('p','Search the national 211 resource locator for your area: ');link('Open 211 locator','https://www.211.org/about-us/your-local-211',p);body.append(p);message('Enter '+zip.value+' on the official locator. Habesha Hub does not have a live ZIP database.');},body);[['Central Ohio support','Food, housing and other community resource connections.','https://lssnetworkofhope.org/211centralohio/'],['Ohio 211','Find your local 211 service across Ohio.','https://ohio211.org/how-to-find-help/'],['Nationwide help','Find a local 211 service outside Ohio.','https://www.211.org/about-us/your-local-211']].forEach(([t,d,u])=>{const card=E('article',undefined,'resource');card.append(E('h3',t),E('p',d));link('Visit official resource',u,card);body.append(card);});link('Call 211','tel:211',body);},
phrases(){tip('A curated phrase guide, not a general translator. Pronunciation spellings are approximate. For important medical or legal conversations, request a qualified interpreter.');const phrases=[['Hello / peace','ሰላም','Selam','General'],['Thank you','አመሰግናለሁ','Ameseginalehu','General'],['Please','እባክዎ','Ebakwo','General'],['I do not understand','አልገባኝም','Algebagnim','General'],['Please speak slowly','እባክዎ ቀስ ብለው ይናገሩ','Ebakwo kes blew yinageru','General'],['I need an interpreter','አስተርጓሚ እፈልጋለሁ','Aster gwami efeligalehu','Appointments'],['How much is it?','ስንት ነው?','Sint new?','Shopping'],['Where is the restroom?','መጸዳጃ ቤቱ የት ነው?','Metse daja betu yet new?','General'],['I have an appointment','ቀጠሮ አለኝ','Ketero alegn','Appointments'],['What time?','ስንት ሰዓት?','Sint seat?','Work & school']];const label=E('label','Search English, Amharic or pronunciation');const input=E('input');input.type='search';label.append(input);body.append(label);const list=E('div',undefined,'items');body.append(list);function render(){list.replaceChildren();const found=phrases.filter(p=>p.join(' ').toLowerCase().includes(input.value.toLowerCase()));found.forEach(p=>{const c=E('div',undefined,'phrase');c.append(E('strong',p[1]),E('p',p[0]),E('small',p[2]+' · '+p[3]));button('Hear English',()=>{if(!window.speechSynthesis){message('Speech is unavailable in this browser.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(p[0]);u.lang='en-US';speechSynthesis.speak(u);},c);button('Copy phrase',async()=>{try{await navigator.clipboard.writeText(p[0]+' — '+p[1]);message('Phrase copied.');}catch{message('Clipboard unavailable. Select the phrase and copy it manually.');}},c);list.append(c);});if(!found.length)list.append(E('p','No matching phrases.'));}input.addEventListener('input',render);render();},
jobs(){formFor('jobs',[{name:'company',label:'Employer',required:true},{name:'title',label:'Role',required:true},{name:'date',label:'Application date',type:'date',required:true},{name:'followup',label:'Follow-up date',type:'date'},notes]);list('jobs',(r,c)=>{c.append(E('h3',r.title+' · '+r.company),E('p','Applied '+dateText(r.date)),E('p','Follow up: '+dateText(r.followup)),E('p',r.notes));const l=E('label','Application status'),s=E('select');['Applied','Interview','Offer','Closed'].forEach(t=>s.append(E('option',t)));s.value=r.state||'Applied';s.addEventListener('change',()=>{r.state=s.value;save();message('Application status saved.');});l.append(s);c.append(l);});},
family(){formFor('family',[title,{name:'person',label:'Person / nickname',required:true},date,{name:'category',label:'Task type',options:['Homework','School activity','Chore','Family appointment']},notes]);list('family',(r,c)=>{c.append(E('h3',r.title),E('p',r.person+' · '+r.category+' · '+dateText(r.date)),E('p',r.notes));button(r.done?'Mark unfinished':'Mark complete',()=>{r.done=!r.done;save();show(current);},c);if(r.done)c.classList.add('completed');});},
scam(){tip('This checklist cannot prove a message or website is safe. Do not enter passwords, account numbers or private messages here.');const box=E('fieldset');box.append(E('legend','Does the message include any of these warning signs?'));['Unexpected urgent demand or threat','Request for passwords or verification codes','Payment by gift card, cryptocurrency or wire transfer','Unfamiliar link or sender address','Prize, job or investment that sounds too good to be true','Pressure to keep the conversation secret'].forEach(t=>{const l=E('label',undefined,'check'),i=E('input');i.type='checkbox';l.append(i,document.createTextNode(t));box.append(l);});body.append(box);const result=E('p');button('Review warning signs',()=>{const n=[...box.querySelectorAll('input')].filter(i=>i.checked).length;result.textContent=n?n+' warning sign(s) selected. Pause. Contact the organization using a number or website you already trust; do not use the message’s link.':'No signs selected. That does not establish safety. Verify unexpected requests through an independent trusted contact.';},body);body.append(result);tip('Already sent money? Contact your bank or payment service immediately. If a password was shared, change it through the real website and enable multi-factor authentication.');link('FTC scam guidance','https://consumer.ftc.gov/scams-identity-theft',body);body.append(E('br'));link('Report fraud to the FTC','https://reportfraud.ftc.gov/',body);body.append(E('br'));link('Identity theft recovery','https://www.identitytheft.gov/',body);},
events(){const sources=E('div',undefined,'resource');sources.append(E('h3','Discover community events'));link('Habesha Hub events','events.html',sources);link('Columbus Library calendar','https://events.columbuslibrary.org/events',sources);body.append(sources);tip('Your saved calendar is personal. It is not a live event feed and does not publish to the community. Confirm event details with the organizer.');formFor('events',[title,date,{name:'location',label:'Location',required:true},notes],'Save an event');calendarButton('events');list('events',(r,c)=>c.append(E('h3',r.title),E('p',dateText(r.date)+' · '+r.location),E('p',r.notes)));},
requests(){tip('Personal request drafts only. These entries are not submitted, published or sent to providers. A moderated shared board will need a future upgrade. Avoid home addresses and private contact information.');formFor('requests',[title,{name:'category',label:'Service',options:['Home','Auto','Professional','Childcare','Beauty']},{name:'city',label:'City / area',required:true},{name:'notes',label:'Describe the work without private details',type:'textarea',required:true}],'Save request draft');list('requests',(r,c)=>{c.append(E('h3',r.title),E('p',r.category+' · '+r.city),E('p',r.notes));link('Find providers in directory','./?q='+encodeURIComponent(r.city)+'&category='+encodeURIComponent(r.category)+'#directory',c);button('Download request draft',()=>download('service-request.txt',[r.title,r.category,r.city,r.notes,'Personal draft — not submitted through Habesha Hub'].join('\n')) ,c);});}
};
$('exportAll').addEventListener('click',()=>download('habesha-daily-life.json',JSON.stringify(data,null,2),'application/json'));
$('clearAll').addEventListener('click',()=>$('clearDialog').showModal());$('cancelClear').addEventListener('click',()=>$('clearDialog').close());$('confirmClear').addEventListener('click',()=>{names.forEach(k=>data[k]=[]);try{localStorage.removeItem(KEY);}catch{}$('clearDialog').close();show(current);message('All Daily Life Tools data cleared from this browser.');});$('print').addEventListener('click',()=>window.print());show(location.hash.slice(1));if(!storageOK)message('Browser storage unavailable. Entries will last only during this visit; download before leaving.');
window.HabeshaDaily={calendar,icsEscape};
})();
