// Habesha Hub community directory data (schema v2)
// One listing per line. Edit carefully, then run:  node tools/validate-data.js
//
// Fields: id (stable, never reuse), name, altNames[], category, subcategory, denomination (churches only:
// Orthodox | Protestant | Catholic, leave empty if not confirmed), address (street only), city, state (full name),
// zip, phone (public business line only), website, social, mapsUrl, source (URL used to verify),
// secondSource, status, verifiedDate (YYYY-MM-DD the details were last checked), publicNote (shown on card),
// notes (internal, not shown), privacy ("limited" hides street/phone for individual providers), keywords[].
//
// status: verified | community | needs-review | temporarily-closed | closed | duplicate
//   verified            current official or strong independent source confirms name, location and Ethiopian connection
//   community           publicly listed (directory, social page) but not independently confirmed
//   needs-review        incomplete, conflicting or unconfirmed details; keep until evidence decides
//   temporarily-closed  shown with a warning
//   closed / duplicate  kept for audit history, hidden from the site
window.HABESHA_META = {"schemaVersion":2,"updated":"2026-09-28"};

window.HABESHA_LISTINGS = [
  {"id":"oh-columbus-habesha-market","name":"Habesha Market","category":"Grocery","subcategory":"Ethiopian market and traditional clothing","address":"1391 S Hamilton Rd","city":"Columbus","state":"Ohio","zip":"43227","source":"https://www.yelp.com/biz/habesha-market-columbus","secondSource":"https://www.facebook.com/kemisnetela/","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp lists as Ethiopian at 1391 S Hamilton Rd (updated Jun 2026); Facebook page 'Habesha market LLC'. Phone 614-867-5990 appears only on Buzzfile, not added."},
  {"id":"oh-columbus-addis-ababa-grocery","name":"Addis Ababa Grocery","category":"Grocery","subcategory":"Ethiopian grocery","address":"157 Fairway Blvd","city":"Whitehall","state":"Ohio","zip":"43213","phone":"(614) 577-0867","website":"https://addisababagrocery.com/","source":"https://addisababagrocery.com/","status":"verified","verifiedDate":"2026-09-28","notes":"Official website gives address and phone. Previously listed with no address.","metro":"Columbus"},
  {"id":"oh-columbus-dire-dawa-grocery-store","name":"Dire Dawa Grocery Store","altNames":["Dire Dawa Grocery and Restaurant","Dire Dawa Store"],"category":"Grocery","subcategory":"Ethiopian grocery","address":"4513 E Main St","city":"Whitehall","state":"Ohio","zip":"43213","phone":"(614) 237-3794","social":"https://www.facebook.com/p/DIRE-DAWA-STORE-61566548710523/","source":"https://www.yelp.com/biz/dire-dawa-grocery-and-restaurant-whitehall","secondSource":"https://diredawagrocerycolumbus.wordpress.com/about/","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp (updated Dec 2025) and store website agree on 4513 E Main St. Phone from store website (2017); confirm on next check.","metro":"Columbus"},
  {"id":"oh-columbus-lalibela-grocery","name":"Lalibela Grocery","category":"Grocery","subcategory":"Ethiopian grocery","address":"1107 S Hamilton Rd","city":"Columbus","state":"Ohio","zip":"43227","phone":"(614) 235-7330","source":"https://m.m.yelp.com/biz/lalibela-grocery-columbus/","secondSource":"https://lalibelagrocery.wordpress.com/about/","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp updated Jul 2026; store website gives address and phone."},
  {"id":"oh-columbus-st-michael-ethiopian-orthodox-church","name":"St. Michael Ethiopian Orthodox Church","category":"Church","denomination":"Orthodox","city":"Columbus","state":"Ohio","status":"duplicate","verifiedDate":"2026-09-28","notes":"Duplicate of oh-columbus-saint-michael-ethiopian-orthodox-tewahedo-church (same congregation, columbusmichael.org). Kept for audit history."},
  {"id":"oh-columbus-debre-medhanit-medhane-alem","name":"Debre Medhanit Medhane Alem","category":"Church","denomination":"Orthodox","address":"610 Neil Ave","city":"Columbus","state":"Ohio","status":"duplicate","verifiedDate":"2026-09-28","notes":"Duplicate of oh-columbus-debre-medihanit-medhanealem-ethiopian-orthodox-tewahedo-church. Yelp still shows 610 Neil Ave; IRS/GuideStar record uses 4295 E Broad St. Kept for audit history."},
  {"id":"oh-columbus-kidest-sehalte-mehret-st-urael","name":"Kidest Sehalte Mehret & St. Urael","altNames":["Salite Meheret Mariyam Kidus Urael Ethiopia Orthodox Tewahdo Church"],"category":"Church","denomination":"Orthodox","address":"7457 E Main St","city":"Reynoldsburg","state":"Ohio","zip":"43068","social":"http://kidestmariamohio.blogspot.com/","source":"https://www.guidestar.org/profile/46-1112432","secondSource":"http://kidestmariamohio.blogspot.com/","status":"needs-review","verifiedDate":"2026-09-28","notes":"IRS/GuideStar mailing address 7457 E Main St #7467 Reynoldsburg (ruling 2013). Church blog last updated ~2011. Need current service location.","metro":"Columbus"},
  {"id":"dc-washington-selam-international-market","name":"Selam International Market","category":"Grocery","address":"7616 Georgia Ave NW","city":"Washington","state":"District of Columbia","zip":"20012","source":"https://habeshalink.com/ethiopian-markets-and-shops-in-dc-md-and-va/","secondSource":"https://www.loopnet.com/Listing/7612-7616-Georgia-Ave-NW-Washington-DC/35877194/","status":"needs-review","verifiedDate":"2026-09-28","publicNote":"We could not confirm this market is still open. Call before visiting.","notes":"Only source is a 2013 HabeshaLink list (7616 Georgia Ave NW, (202) 722-2792). The 7612-7616 Georgia Ave building later appeared as a retail sale listing. No current listing found. Candidate for CLOSED if a second source confirms."},
  {"id":"va-springfield-merkato-ethiopian-market","name":"Merkato Ethiopian Market & Kitchen","altNames":["Merkato Market Grocery & Carry Out Food"],"category":"Grocery","subcategory":"Ethiopian grocery and carryout","address":"6816 Bland St","city":"Springfield","state":"Virginia","zip":"22150","phone":"(703) 663-8635","website":"https://www.springfieldmerkato.com/","source":"https://www.springfieldmerkato.com/","secondSource":"https://www.yelp.com/biz/merkato-market-grocery-and-carry-out-food-springfield","status":"verified","verifiedDate":"2026-09-28","notes":"Official site gives address and phone. Previously listed with no address."},
  {"id":"md-silver-spring-tana-ethiopian-market","name":"Tana Market","altNames":["Tana Ethiopian Market"],"category":"Grocery","subcategory":"Ethiopian grocery","address":"623 Sligo Ave","city":"Silver Spring","state":"Maryland","zip":"20910","phone":"(301) 562-9322","source":"https://www.yelp.com/biz/tana-market-silver-spring","secondSource":"https://www.waze.com/live-map/directions/tana-market-sligo-ave-623-silver-spring?to=place.w.185467270.1854607163.1095844","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp updated Jun 2026 and map listing agree on 623 Sligo Ave. Phone matches business directories."},
  {"id":"va-falls-church-skyline-international-market","name":"Skyline International Market","category":"Grocery","address":"3819 S George Mason Dr, Suite C","city":"Falls Church","state":"Virginia","zip":"22041","source":"https://habeshalink.com/ethiopian-markets-and-shops-in-dc-md-and-va/","status":"needs-review","verifiedDate":"2026-09-28","publicNote":"We could not confirm this market is still open. Call before visiting.","notes":"Only a 2013 HabeshaLink list found ((703) 933-0040). Not the same business as Skyline Cafe (3821 S George Mason Dr). Candidate for CLOSED."},
  {"id":"dc-washington-chercher-ethiopian-restaurant-mart","name":"Chercher Ethiopian Restaurant & Mart","category":"Restaurant","subcategory":"Ethiopian restaurant and market","address":"1334 9th St NW","city":"Washington","state":"District of Columbia","zip":"20001","phone":"(202) 299-9703","website":"https://chercherrestaurant.com/","source":"https://chercherrestaurant.com/","secondSource":"https://www.yelp.com/biz/chercher-ethiopian-restaurant-and-mart-washington","status":"verified","verifiedDate":"2026-09-28","notes":"Official site lists Shaw location 1334 9th St NW (202) 299-9703; Yelp updated Sep 2026."},
  {"id":"dc-washington-habesha-market-carry-out-restaurant","name":"Habesha Market & Carry-out","altNames":["Habesha Market Carry Out & Restaurant"],"category":"Restaurant","subcategory":"Ethiopian carryout and market","address":"1919 9th St NW","city":"Washington","state":"District of Columbia","zip":"20001","phone":"(202) 232-1919","source":"https://toast.app/r/habesha-market-carry-out-1919-9th-st-nw","secondSource":"https://www.yelp.com/biz/habesha-market-and-carry-out-washington","status":"verified","verifiedDate":"2026-09-28","notes":"Toast ordering page open and accepting orders; Yelp updated Aug 2026."},
  {"id":"dc-washington-shewa-ethiopian-restaurant","name":"Shewa Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant and carryout","address":"1824 Benning Rd NE","city":"Washington","state":"District of Columbia","zip":"20002","phone":"(202) 450-4606","website":"https://shewarestaurant.com/","source":"https://shewarestaurant.com/","secondSource":"https://www.yelp.com/biz/shewa-washington","status":"verified","verifiedDate":"2026-09-28","notes":"Official site address and phone; Yelp updated Jun 2026."},
  {"id":"dc-washington-intoto-ethiopian-restaurant-and-market","name":"Intoto Market & Carryout","altNames":["Intoto Ethiopian Restaurant and Market"],"category":"Grocery","subcategory":"Ethiopian grocery and carryout","address":"6406 Georgia Ave NW","city":"Washington","state":"District of Columbia","zip":"20012","phone":"(202) 545-5027","website":"https://intotodc.wordpress.com/","source":"https://www.yelp.com/biz/intoto-market-and-carryout-washington","secondSource":"https://intotodc.wordpress.com/","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp updated Jul 2026; store site gives phone."},
  {"id":"dc-washington-debre-selam-kidist-mariam-ethiopian-orthodox-tewahedo-church","name":"Debre Selam Kidist Mariam Ethiopian Orthodox Tewahedo Church","altNames":["Re'ese Adbarat Debre Selam Kidist Mariam","DSK Mariam"],"category":"Church","denomination":"Orthodox","address":"1350 Buchanan St NW","city":"Washington","state":"District of Columbia","zip":"20011","phone":"(202) 726-4115","website":"https://dskmariamdc.org/","source":"https://dskmariamdc.org/contact/","secondSource":"https://www.yelp.com/biz/debre-selam-kidist-mariam-church-ethiopian-orthodox-washington","status":"verified","verifiedDate":"2026-09-28","notes":"Official contact page. Zip corrected 20011 (per church site)."},
  {"id":"dc-washington-debre-meheret-kedus-michael-ethiopian-orthodox-cathedral","name":"Debre Meheret Kedus Michael Ethiopian Orthodox Cathedral","category":"Church","denomination":"Orthodox","address":"3010 Earl Pl NE","city":"Washington","state":"District of Columbia","zip":"20018","website":"https://kidusmichaeldc.org/","social":"https://www.facebook.com/debremehretdc/","source":"https://everloved.com/funeral-venues/DC/washington/debre-meheret-kedus-michael-ethiopian-orthodox-cathedral-washington-dc-20018/","secondSource":"https://www.waze.com/live-map/directions/debre-meheret-kedus-michael-ethiopian-orthodox-cathedral-earl-pl-ne-3010-washington?to=place.w.185467269.1854934837.1453354","status":"verified","verifiedDate":"2026-09-28","notes":"Address confirmed by venue directory and map listing; website kidusmichaeldc.org."},
  {"id":"dc-washington-international-ethiopian-evangelical-church","name":"International Ethiopian Evangelical Church","altNames":["IEEC"],"category":"Church","denomination":"Protestant","address":"7930 Eastern Ave NW","city":"Washington","state":"District of Columbia","zip":"20012","phone":"(202) 726-8529","website":"https://www.eecdc.org/","source":"https://www.eecdc.org/visit-us","secondSource":"https://www.youtube.com/@ieecwashingtondc","status":"verified","verifiedDate":"2026-09-28","notes":"Official site: 7930 Eastern Ave NW, Sundays 9am and 11:30am."},
  {"id":"md-mount-rainier-adot-international-market","name":"ADOT International Market","category":"Grocery","subcategory":"Ethiopian and Eritrean grocery","address":"3111 Chillum Rd","city":"Mount Rainier","state":"Maryland","zip":"20712","website":"https://myadot.com/","social":"https://www.instagram.com/adotmarket/","source":"https://myadot.com/","secondSource":"https://www.yelp.com/biz/adot-international-market-mount-rainier","status":"verified","verifiedDate":"2026-09-28","notes":"Official site: family-owned Ethiopian grocery at 3111 Chillum Rd."},
  {"id":"md-silver-spring-beteseb-restaurant","name":"Beteseb Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"8201 Georgia Ave","city":"Silver Spring","state":"Maryland","zip":"20910","phone":"(301) 448-1625","website":"https://www.betesebrestaurant.com/","source":"https://www.betesebrestaurant.com/contact-us","secondSource":"https://washingtonian.com/100-very-best-restaurants-2025/beteseb-2/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"md-silver-spring-abyssinia-ethiopian-restaurant","name":"Abyssinia Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"8221 Georgia Ave","city":"Silver Spring","state":"Maryland","zip":"20910","phone":"(301) 562-5911","social":"https://www.facebook.com/p/Abyssinia-Restaurant-Bar-100086486662417/","source":"https://silverspringdowntown.com/go/abyssinia-ethiopian-restaurant","secondSource":"https://www.yelp.com/biz/abyssinia-restaurant-silver-spring-2","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"md-silver-spring-sheger-spring-cafe","name":"Sheger Spring Cafe","category":"Restaurant","subcategory":"Ethiopian cafe","address":"900 Silver Spring Ave, Suite B","city":"Silver Spring","state":"Maryland","zip":"20910","phone":"(301) 844-5740","website":"https://www.shegerspringcafe.com/","source":"https://www.shegerspringcafe.com/address","secondSource":"https://www.yelp.com/biz/sheger-spring-cafe-silver-spring-3","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"md-silver-spring-langano-ethiopian-restaurant","name":"Langano Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"8305 Georgia Ave","city":"Silver Spring","state":"Maryland","zip":"20910","phone":"(301) 563-6700","website":"https://www.langanoethiopianrestaurant.com/","source":"https://www.langanoethiopianrestaurant.com/","secondSource":"https://www.yelp.com/biz/langano-ethiopian-restaurant-silver-spring","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"md-silver-spring-woder-ethiopian-carryout-market","name":"Woder Ethiopian Carryout & Market","altNames":["Woder Ethiopia Carry Out and Restaurant"],"category":"Restaurant","subcategory":"Ethiopian carryout and market","address":"7845 Eastern Ave","city":"Silver Spring","state":"Maryland","zip":"20910","phone":"(301) 562-5901","source":"https://silverspringdowntown.com/go/woder-ethiopian-carryout-and-market","secondSource":"https://www.yelp.com/biz/woder-ethiopia-carry-out-and-restaurant-silver-spring","status":"verified","verifiedDate":"2026-09-28","notes":"Category changed Grocery to Restaurant: Yelp and downtown directory list it primarily as a carryout restaurant with market."},
  {"id":"va-alexandria-zema-market","name":"Zema Market","category":"Grocery","subcategory":"Ethiopian grocery","address":"8714 Richmond Hwy","city":"Alexandria","state":"Virginia","zip":"22309","phone":"(571) 347-7072","website":"https://www.zemamarket.com/","source":"https://www.zemamarket.com/","secondSource":"https://patch.com/virginia/greateralexandria/zema-market-brings-ethiopian-products-richmond-highway","status":"verified","verifiedDate":"2026-09-28","notes":"Official site lists address, phone and hours, no closure notice. The 8714 Richmond Hwy building appears in real-estate sale listings; recheck in 3 months."},
  {"id":"va-alexandria-zemeda-market-and-restaurant","name":"ZeMeda Market and Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant and market","address":"512 S Van Dorn St, Suite B","city":"Alexandria","state":"Virginia","zip":"22304","phone":"(703) 212-6740","website":"https://www.zemedamarket.com/","source":"https://www.zemedamarket.com/","secondSource":"https://www.eatokra.com/businesses/zemeda-market-and-restaurant","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"va-lincolnia-time-ethiopian-cafe-and-market","name":"Time Ethiopian Cafe and Market","altNames":["Time Cafe"],"category":"Restaurant","subcategory":"Ethiopian restaurant, butcher and market","address":"4701 N Chambliss St","city":"Alexandria","state":"Virginia","zip":"22312","phone":"(571) 506-3299","website":"https://timecafeva.com/","source":"https://timecafeva.com/","secondSource":"https://www.yelp.com/biz/time-ethiopian-cafe-alexandria","status":"verified","verifiedDate":"2026-09-28","notes":"Mailing city is Alexandria per official site (Lincolnia area).","keywords":["Lincolnia"]},
  {"id":"va-falls-church-regal-abyssinia","name":"Regal Abyssinia","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"3821 S George Mason Dr, Suite B","city":"Falls Church","state":"Virginia","zip":"22041","website":"https://regalabyssinia.com/","social":"https://www.instagram.com/regalabyssinia/","source":"https://www.ubereats.com/store/regal-abyssinia-restaurant-3821b-s-george-mason-dr/MJP84GlCWl6P9qkuk5vPDQ","secondSource":"https://www.fairfaxtimes.com/public_notices/regal-abyssinia-abc-notice/image_8278f40e-08a9-11ef-8a6e-5f30b0a309c4.html","status":"verified","verifiedDate":"2026-09-28","notes":"Ordering listing at 3821B S George Mason Dr; ABC license notice. Official site is JavaScript-only, phone not captured."},
  {"id":"va-arlington-dama-restaurant-and-pastry","name":"Dama Restaurant and Pastry","altNames":["Dama Pastry & Cafe","Dama Bakery"],"category":"Restaurant","subcategory":"Ethiopian cafe and bakery","address":"1505 Columbia Pike","city":"Arlington","state":"Virginia","zip":"22204","phone":"(703) 920-5620","website":"https://www.damapastry.com/","source":"https://www.damapastry.com/","secondSource":"https://www.yelp.com/biz/dama-bakery-arlington","status":"verified","verifiedDate":"2026-09-28","notes":"Official site: 'Arlington's traditional Ethiopian cafe'. Address/phone from Yelp (updated Jun 2026)."},
  {"id":"va-alexandria-hawwi-ethiopian-restaurant","name":"Hawwi Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"1125 Queen St","city":"Alexandria","state":"Virginia","zip":"22314","phone":"(703) 717-9740","website":"https://www.eathawirestaurant.com/","source":"https://www.eathawirestaurant.com/","secondSource":"https://www.yelp.com/biz/hawwi-ethiopian-restaurant-alexandria","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"va-sterling-gospel-believers-ethiopian-church","name":"Gospel Believers Ethiopian Church","category":"Church","subcategory":"Evangelical (Southern Baptist affiliated)","denomination":"Protestant","address":"45305 Catalina Ct, Unit 190","city":"Sterling","state":"Virginia","zip":"20166","phone":"(571) 315-3502","website":"https://gbec.church/","source":"https://gbec.church/","secondSource":"https://www.sbcv.org/churches/gospel-believers-ethiopian-church/","status":"verified","verifiedDate":"2026-09-28","notes":"ADDRESS CORRECTED from 1402 Shepard Dr to the church's current address on its official website."},
  {"id":"va-annandale-virginia-evangelical-lutheran-church-mekane-yesus","name":"Virginia Evangelical Lutheran Church Mekane Yesus","category":"Church","subcategory":"Lutheran (Mekane Yesus)","denomination":"Protestant","address":"6005 Tower Ct","city":"Alexandria","state":"Virginia","zip":"22304","phone":"(571) 319-0562","website":"https://www.velcmy.com/","source":"https://www.velcmy.com/get-directions","secondSource":"https://locator.lcms.org/church/C/1001824","status":"verified","verifiedDate":"2026-09-28","notes":"ADDRESS CORRECTED from 3901 Gallows Rd, Annandale (LCMS locator, older) to 6005 Tower Ct, Alexandria per official website."},
  {"id":"ga-atlanta-embilta-cafe-restaurant","name":"Embilta Cafe & Restaurant","altNames":["Embilta Ethiopian Cafe & Restaurant"],"category":"Restaurant","subcategory":"Ethiopian restaurant and cafe","address":"2100 Cheshire Bridge Rd NE, Suite A","city":"Atlanta","state":"Georgia","zip":"30324","website":"https://embiltarestaurant.com/","source":"https://www.yelp.com/biz/embilta-caf%C3%A9-and-restaurant-ethiopian-cuisine-atlanta","secondSource":"https://www.grubhub.com/restaurant/embilta-caf--restaurant-2100-cheshire-bridge-rd-ne-suite-a-atlanta/337390","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp (224 reviews, updated Aug 2026). A separate old Yelp page 'Embilta' (coffee) is marked closed; it is not this restaurant."},
  {"id":"ga-stone-mountain-ethiopian-evangelical-church-atlanta","name":"Ethiopian Evangelical Church Atlanta","altNames":["Ethiopian Evangelical Church of Atlanta","EEC Atlanta"],"category":"Church","subcategory":"Evangelical (US Mennonite Brethren)","denomination":"Protestant","address":"4550 Greer Cir","city":"Stone Mountain","state":"Georgia","zip":"30083","phone":"(770) 496-1665","website":"https://eecatlanta.com/","source":"https://eecatlanta.com/prek/","secondSource":"https://usmb.org/church/ethiopian-evangelical-church/","status":"verified","verifiedDate":"2026-09-28","notes":"Official site footer: 4550 Greer Cir, Stone Mountain 30083, 770-496-1665.","metro":"Atlanta"},
  {"id":"ga-stone-mountain-ebenezer-ethiopian-evangelical-church-atlanta","name":"Ebenezer Ethiopian Evangelical Church Atlanta","category":"Church","denomination":"Protestant","address":"4528 Rockbridge Rd SW","city":"Stone Mountain","state":"Georgia","zip":"30083","website":"https://eeeca.org/","social":"https://www.facebook.com/GEGBCAtlanta/","source":"https://eeeca.org/about/","secondSource":"https://www.youtube.com/channel/UCGY7Hgr-RK6ya4HQgS5T3Dw","status":"needs-review","verifiedDate":"2026-09-28","publicNote":"Church confirmed; street address not yet confirmed. Check the church website before visiting.","notes":"Congregation confirmed via eeeca.org and YouTube. v1 address '4528 Rockbridge Rd SW' could not be confirmed (site blocked automated fetch). Downgraded from verified.","metro":"Atlanta"},
  {"id":"ga-atlanta-mekane-hiwot-abune-gebre-menfes-kidus-eotc","name":"Mekane Hiwot Abune Gebre Menfes Kidus EOTC","altNames":["Atlanta Abo","Atlanta Mekane Hiwot Abune Gebre Menfes Kidus Cathedral"],"category":"Church","denomination":"Orthodox","address":"4575 Stonegate Industrial Blvd","city":"Stone Mountain","state":"Georgia","zip":"30083","phone":"(678) 609-3682","website":"https://www.atlantaabo.org/","social":"https://www.facebook.com/AtlantaAbo/","source":"https://www.atlantaabo.org/Home/About","secondSource":"https://www.youtube.com/@atlabo","status":"verified","verifiedDate":"2026-09-28","notes":"ADDRESS ADDED from official site (v1 had 'Atlanta, GA' only). Note: aboeotc.org / GuideStar 80-0650951 is a different church of the same name in Norfolk, VA.","metro":"Atlanta"},
  {"id":"tx-dallas-desta-ethiopian-restaurant","name":"Desta Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"12101 Greenville Ave, Suite 105","city":"Dallas","state":"Texas","zip":"75243","phone":"(214) 575-9004","website":"https://destadallasethiopian.com/","source":"https://destadallasethiopian.com/","secondSource":"https://www.yelp.com/biz/desta-ethiopian-restaurant-dallas-2","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"tx-dallas-abyssinia-grocery-and-ethiopian-food","name":"Abyssinia Grocery and Ethiopian Food","altNames":["Abyssinia Gebya"],"category":"Grocery","subcategory":"Ethiopian grocery and food","address":"9191 Forest Ln, Suite 1A","city":"Dallas","state":"Texas","zip":"75243","source":"https://www.ubereats.com/store/abyssinia-grocery-and-ethiopian-food-9191-forest-ln-1a-dallas-tx-75243/eBBt1JJhQkmH4mlOkzMJKQ","secondSource":"https://www.yelp.com/biz/abyssinia-gebya-dallas","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"tx-dallas-awudamet-market","name":"Awudamet Market","altNames":["አውዳመት ገበያ"],"category":"Grocery","subcategory":"Ethiopian market","address":"9751 Walnut St, Unit 102","city":"Dallas","state":"Texas","zip":"75243","social":"https://www.facebook.com/61568767259894/","source":"https://www.facebook.com/61568767259894/posts/9751-walnut-st-dallas-tx-75243/122118204530625575/","status":"community","verifiedDate":"2026-09-28","notes":"Only the business's own Facebook page confirms location. Downgraded from verified until a second source (map/listing) is found."},
  {"id":"tx-garland-debre-mehret-st-michael-ethiopian-orthodox-tewahedo-cathedral","name":"Debre Mehret St. Michael Ethiopian Orthodox Tewahedo Cathedral","category":"Church","denomination":"Orthodox","address":"1106 N Jupiter Rd","city":"Garland","state":"Texas","zip":"75042","social":"https://www.facebook.com/DallasMichaeleotc/","source":"https://www.guidestar.org/profile/75-2440445","secondSource":"https://www.facebook.com/DallasMichaeleotc/","status":"verified","verifiedDate":"2026-09-28","notes":"IRS/GuideStar record and church Facebook page.","metro":"Dallas"},
  {"id":"tx-garland-ethiopian-evangelical-believers-church","name":"Ethiopian Evangelical Believers Church","altNames":["EEBC Dallas","Ethiopian Evangelical Baptist Church"],"category":"Church","subcategory":"Evangelical","denomination":"Protestant","address":"3001 Saturn Rd","city":"Garland","state":"Texas","zip":"75041","website":"http://wongelkedallas.org/","social":"https://www.facebook.com/p/EEBC-Dallas-100077290596111/","source":"https://www.guidestar.org/profile/75-2328171","secondSource":"https://www.facebook.com/p/EEBC-Dallas-100077290596111/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","metro":"Dallas"},
  {"id":"tx-houston-blue-nile","name":"Blue Nile Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"3030 Audley St","city":"Houston","state":"Texas","zip":"77098","phone":"(713) 814-5101","website":"https://www.bluenilerestaurant.com/","source":"https://www.bluenilerestaurant.com/","secondSource":"https://www.yelp.com/biz/blue-nile-houston-5","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"tx-houston-bahel-ethiopian-mart-and-dining","name":"Bahel Ethiopian Mart and Dining","category":"Restaurant","subcategory":"Ethiopian restaurant and market","address":"6509 Chimney Rock Rd","city":"Houston","state":"Texas","zip":"77081","phone":"(713) 234-6527","source":"https://www.yelp.com/biz/bahel-ethiopian-mart-and-dining-houston","secondSource":"https://www.texasmonthly.com/restaurant/bahel-ethiopian-mart-and-dining/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"tx-houston-selam-ethio-eritrea-specialty-store","name":"Selam Ethio-Eritrea Specialty Store","category":"Shopping","subcategory":"Ethiopian and Eritrean clothing and specialty goods","address":"5701 Bellaire Blvd, Suite D","city":"Houston","state":"Texas","zip":"77081","website":"https://selamspecialty.com/","source":"https://selamspecialty.com/about-us/we-re-dedicated-to-excellence-6454785","secondSource":"https://www.yelp.com/biz/selam-ethio-eritrea-speciality-store-houston","status":"verified","verifiedDate":"2026-09-28","notes":"Category changed Grocery to Shopping: listed as a specialty/fashion retail store."},
  {"id":"tx-houston-debre-selam-medhane-alem-ethiopian-orthodox-tewahedo-church","name":"Debre Selam Medhane Alem Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"11614 Canemont St","city":"Houston","state":"Texas","zip":"77035","phone":"(713) 728-2333","website":"https://houstonmedhanealem.org/","source":"https://houstonmedhanealem.org/","secondSource":"https://www.facebook.com/Houstonmedhanealem/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"tx-houston-holy-trinity-and-saint-mary-ethiopian-orthodox-tewahedo-church","name":"Holy Trinity and Saint Mary Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"8231 McGee Ln","city":"Houston","state":"Texas","zip":"77071","website":"https://holytrinitystmary.org/","social":"https://www.facebook.com/p/Holy-Trinity-and-Saint-Mary-Ethiopian-Orthodox-Tewahedo-Church-100068433464657/","source":"https://holytrinitystmary.org/about-the-church/","secondSource":"https://www.charitynavigator.org/ein/473553023","status":"community","verifiedDate":"2026-09-28","notes":"Church and website confirmed; street address 8231 McGee Ln comes from map directories only (official site timed out). Downgraded from verified."},
  {"id":"tx-houston-ethiopian-community-organization-in-houston","name":"Ethiopian Community Organization in Houston","altNames":["ECOH"],"category":"Community","subcategory":"Community association","address":"6671 Southwest Fwy, Suite 439","city":"Houston","state":"Texas","zip":"77074","phone":"(832) 277-2360","website":"https://www.ecohouston.org/","source":"https://www.ecohouston.org/","secondSource":"https://www.guidestar.org/profile/76-0583932","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"wa-seattle-delish-ethiopian-cuisine","name":"Delish Ethiopian Cuisine","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"5701 Rainier Ave S","city":"Seattle","state":"Washington","zip":"98118","phone":"(206) 723-3821","website":"https://delishethiopianfood.com/","source":"https://delishethiopianfood.com/","secondSource":"https://www.yelp.com/biz/delish-ethiopian-cuisine-seattle-2","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"wa-seattle-jebena-cafe","name":"Jebena Cafe","category":"Restaurant","subcategory":"Ethiopian restaurant and cafe","address":"1510 NE 117th St","city":"Seattle","state":"Washington","zip":"98125","phone":"(206) 365-0757","website":"https://jebenacafe.com/","source":"https://jebenacafe.com/directions/","secondSource":"https://www.yelp.com/biz/jebena-cafe-seattle","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"wa-seattle-nazareth-market","name":"Nazareth Market","category":"Grocery","subcategory":"Ethiopian grocery and deli","address":"5418 Martin Luther King Jr Way S","city":"Seattle","state":"Washington","zip":"98118","source":"https://www.yelp.com/biz/nazareth-market-seattle-2","secondSource":"https://www.selamlist.com/business/nazareth-market-seattle","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp (Ethiopian category, updated Aug 2026) and SelamList Habesha directory."},
  {"id":"wa-seattle-east-african-imports-restaurant","name":"East African Imports & Restaurant","category":"Grocery","subcategory":"Ethiopian restaurant and import store","address":"306 23rd Ave S, Suite 104","city":"Seattle","state":"Washington","zip":"98144","source":"https://www.yelp.com/biz/east-african-imports-and-restaurant-seattle","secondSource":"https://www.waze.com/live-map/directions/us/wa/seattle/east-african-imports-and-restaurant?to=place.ChIJn_vTfelqkFQRfsPOJiRMiEM","status":"verified","verifiedDate":"2026-09-28","notes":"Category left as Grocery (imports store with restaurant)."},
  {"id":"wa-seattle-addis-market-seattle","name":"Addis Market","category":"Grocery","subcategory":"Ethiopian grocery","address":"13500 Aurora Ave N, Suite B","city":"Seattle","state":"Washington","zip":"98133","phone":"(206) 367-3162","website":"https://www.addismarketseattle.com/","source":"https://www.addismarketseattle.com/our-store","secondSource":"https://www.yelp.com/biz/addis-market-seattle","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"wa-seattle-ethiopian-community-in-seattle","name":"Ethiopian Community in Seattle","altNames":["ECS"],"category":"Community","subcategory":"Community association and senior services","address":"8323 Rainier Ave S, Suite A","city":"Seattle","state":"Washington","zip":"98118","phone":"(206) 325-0304","website":"https://www.ecseattle.org/","source":"https://www.ecseattle.org/","secondSource":"https://www.wagives.org/organization/ethiopian-community-in-seattle","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"mn-minneapolis-mesob-ethiopian-restaurant","name":"Mesob Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"3915 Hiawatha Ave","city":"Minneapolis","state":"Minnesota","zip":"55406","website":"https://mesobmn.com/","source":"https://www.yelp.com/biz/mesob-ethiopian-restaurant-minneapolis","secondSource":"https://mnblackbusiness.com/businesses/mesob-ethiopian-restaurant/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"mn-minneapolis-the-red-sea-ethiopian-restaurant","name":"The Red Sea Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian and Eritrean restaurant","address":"320 Cedar Ave S","city":"Minneapolis","state":"Minnesota","zip":"55454","phone":"(612) 333-1644","website":"https://theredseampls.com/","source":"https://theredseampls.com/","secondSource":"https://www.yelp.com/biz/the-red-sea-ethiopian-restaurant-minneapolis-3","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"mn-minneapolis-kela-market","name":"KELA Market","category":"Grocery","subcategory":"Ethiopian grocery and cookware","address":"4020 Minnehaha Ave","city":"Minneapolis","state":"Minnesota","zip":"55406","website":"https://kelamarket.com/","social":"https://www.instagram.com/kela.market.mn/","source":"https://www.longfellowwhatever.com/specialty-ethiopian-grocer-opens-at-40th-and-minnehaha/","secondSource":"https://www.instagram.com/kela.market.mn/","status":"verified","verifiedDate":"2026-09-28","notes":"Opened Nov 2025 per Longfellow Whatever."},
  {"id":"mn-minneapolis-shabelle-ethiopian-grocery","name":"Shabelle Ethiopian Grocery","altNames":["Shabelle Grocery","Shabelle Ethiopian Grocery and Restaurant"],"category":"Grocery","subcategory":"Ethiopian grocery and restaurant","address":"2325 E Franklin Ave","city":"Minneapolis","state":"Minnesota","zip":"55406","source":"https://www.yelp.com/biz/shabelle-grocery-minneapolis","secondSource":"https://www.waze.com/en-GB/live-map/directions/shabelle-ethiopian-grocery-and-restaurant-e-franklin-ave-2325-minneapolis?to=place.w.174850498.1748242832.3747323","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"mn-minneapolis-reese-adbarat-tserha-aryam-kidist-selassie-ethiopian-orthodox-tewahedo-cathedral","name":"Re'ese Adbarat Tserha Aryam Kidist Selassie Ethiopian Orthodox Tewahedo Cathedral","altNames":["Holy Trinity Cathedral EOTC Minneapolis"],"category":"Church","denomination":"Orthodox","address":"2601 Minnehaha Ave","city":"Minneapolis","state":"Minnesota","zip":"55406","website":"https://minnesotaselassie.org/","social":"https://www.facebook.com/ReEseAdbaratTserhaAryam/","source":"https://www.guidestar.org/profile/47-0983091","secondSource":"https://www.facebook.com/ReEseAdbaratTserhaAryam/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"mn-minneapolis-debre-selam-medhanealem-ethiopian-orthodox-tewahedo-church","name":"Debre Selam Medhanealem Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"2629 30th Ave S","city":"Minneapolis","state":"Minnesota","zip":"55406","website":"https://www.debreselam.net/","social":"https://www.facebook.com/Debreselameotc/","source":"https://www.longfellownokomismessenger.com/stories/debre-selam-medhanealem-ethiopian-orthodox-tewahedo-churchfinds-new-home-in-seward,161305","secondSource":"https://www.waze.com/live-map/directions/us/mn/minneapolis/debre-selam-medhanealem-ethiopian-orthodox-tewahdo-church?to=place.ChIJfeTHjawp9ocRNULiAMeMEOs","status":"community","verifiedDate":"2026-09-28","publicNote":"The church moved to 2629 30th Ave S (Seward). Its website still shows the older address, 4401 Minnehaha Ave S.","notes":"News article + city land-use application (2024) + map listing support 2629 30th Ave S; church website shows 4401 Minnehaha Ave S, (612) 721-1222. Downgraded until the church site is updated."},
  {"id":"co-aurora-eatopia-eat-ethiopian","name":"Eatopia: Eat Ethiopian","altNames":["Eatopia Ethiopia Food & Coffee"],"category":"Restaurant","subcategory":"Ethiopian restaurant and coffee","address":"1030 Havana St, Unit B","city":"Aurora","state":"Colorado","zip":"80010","phone":"(303) 862-5322","website":"https://eat-opia.com/","source":"https://eat-opia.com/","secondSource":"https://www.yelp.com/biz/eatopia-ethiopia-food-and-coffee-aurora-2","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"co-aurora-gursha-ethiopian-restaurant","name":"Gursha Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"15373 E 6th Ave Unit B","city":"Aurora","state":"Colorado","zip":"80011","phone":"(303) 600-8650","website":"https://www.gurshaethiopianrestaurant.com/","source":"https://www.gurshaethiopianrestaurant.com/","secondSource":"https://www.yelp.com/biz/gursha-ethiopian-restaurant-aurora","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"co-aurora-piassa-retail-store-restaurant","name":"Piassa Retail Store & Restaurant","altNames":["Piassa Ethio Mart","PIASSA Retail Store, Restaurant & Meat Market"],"category":"Grocery","subcategory":"Ethiopian market, butcher and restaurant","address":"601 Salida Way, Unit B5","city":"Aurora","state":"Colorado","zip":"80011","phone":"(303) 593-0056","website":"https://www.piassadenver.com/","source":"https://www.piassadenver.com/contact","secondSource":"https://www.yelp.com/biz/piassa-aurora","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"co-aurora-gihon-international-market","name":"Gihon International Market","category":"Grocery","subcategory":"Ethiopian and Eritrean grocery","address":"16761 E Iliff Ave","city":"Aurora","state":"Colorado","zip":"80013","social":"https://www.facebook.com/Gihonintmarket/","source":"https://www.yelp.com/biz/gihon-international-market-aurora","secondSource":"https://meazafood.com/store/gihon-international-market/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"co-denver-ethiopian-orthodox-tewahedo-debre-selam-medhanealem-church","name":"Ethiopian Orthodox Tewahedo Debre Selam Medhanealem Church","category":"Church","denomination":"Orthodox","address":"5152 E 17th Ave Pkwy","city":"Denver","state":"Colorado","zip":"80220","website":"https://denvermedhanealem.org/","social":"https://www.facebook.com/denvermeotc/","source":"https://www.yelp.com/biz/medhanealem-ethiopian-orthodox-tewahedo-church-denver","secondSource":"https://www.guidestar.org/profile/59-3798077","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"co-aurora-st-mary-ethiopian-orthodox-tewahedo-church","name":"St Mary Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"16250 E Colfax Ave","city":"Aurora","state":"Colorado","zip":"80011","source":"https://orthodox-world.org/en/i/28866/united-states/colorado/aurora/church/st.-mary%E2%80%99s-ethiopian-orthodox-tewahedo-church","secondSource":"https://www.charitynavigator.org/ein/841234649","status":"community","verifiedDate":"2026-09-28","notes":"Directory listings give 16250 E Colfax Ave; Yelp shows 16200 E Colfax Ave. No official website found. Downgraded from verified."},
  {"id":"ca-los-angeles-messob-ethiopian-restaurant","name":"Messob Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"1041 S Fairfax Ave","city":"Los Angeles","state":"California","zip":"90019","phone":"(323) 938-8827","website":"https://www.messob.com/","source":"https://www.messob.com/contact","secondSource":"https://www.yelp.com/biz/messob-ethiopian-restaurant-los-angeles-2","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","keywords":["Little Ethiopia"]},
  {"id":"ca-los-angeles-rosalinds-ethiopian-restaurant","name":"Rosalind's Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"1044 S Fairfax Ave","city":"Los Angeles","state":"California","zip":"90019","website":"https://www.rosalindsla.com/","source":"https://www.yelp.com/biz/rosalinds-ethiopian-restaurant-los-angeles","secondSource":"https://www.discoverlosangeles.com/eat-drink/rosalinds-ethiopian-restaurant","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","keywords":["Little Ethiopia"]},
  {"id":"ca-los-angeles-buna-ethiopian-restaurant-market","name":"Buna Ethiopian Restaurant & Market","category":"Restaurant","subcategory":"Ethiopian restaurant and market","address":"1034 S Fairfax Ave","city":"Los Angeles","state":"California","zip":"90019","phone":"(323) 964-9731","website":"https://bunaethiopianmarket.com/","source":"https://bunaethiopianmarket.com/page/contact-us-","secondSource":"https://www.yelp.com/biz/buna-ethiopian-restaurant-and-market-los-angeles-2","status":"verified","verifiedDate":"2026-09-28","notes":"Category changed Grocery to Restaurant (primarily a restaurant with a market).","keywords":["Little Ethiopia"]},
  {"id":"ca-los-angeles-gojo-ethio-market","name":"Gojo Ethio Market","category":"Grocery","subcategory":"Ethiopian grocery and household goods","address":"3417 S La Brea Ave","city":"Los Angeles","state":"California","zip":"90016","phone":"(323) 325-2993","website":"https://www.gojoethiomarket.com/","source":"https://www.gojoethiomarket.com/contact-us","secondSource":"https://www.waze.com/live-map/directions/us/ca/los-angeles/gojo-ethio-market?to=place.ChIJsxK65RW5woARD69aPaHl0Fc","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"ca-los-angeles-st-marys-ethiopian-orthodox-tewahedo-church","name":"St Mary's Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"5505 W Slauson Ave","city":"Los Angeles","state":"California","zip":"90056","website":"https://www.ethiopianorthodoxchurch.org/","social":"https://www.facebook.com/St.MaryEthiopianOrthodoxChurchLA/","source":"https://locator.lacounty.gov/dcfs/Location/3177141/st-marys-ethiopian-orthodox-tewahedo-church","secondSource":"https://www.waze.com/live-map/directions/st-marys-ethiopian-orthodox-tewahedo-church-w-slauson-ave-5505-ladera-heights?to=place.w.158335316.1583484231.810728","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","keywords":["Ladera Heights"]},
  {"id":"oh-columbus-addis-restaurant","name":"Addis Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"3750 Cleveland Ave","city":"Columbus","state":"Ohio","zip":"43224","phone":"(614) 269-8680","source":"https://www.yelp.com/biz/addis-restaurant-columbus","secondSource":"https://www.tripadvisor.com/Restaurant_Review-g50226-d27918281-Reviews-Addis_Restaurant-Columbus_Ohio.html","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp (171 reviews, updated Jul 2026) and Tripadvisor agree on address; phone from Tripadvisor."},
  {"id":"oh-columbus-the-habesha-garden-restaurant","name":"The Habesha Garden Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"4520 Josephus Ln","city":"Columbus","state":"Ohio","zip":"43227","social":"https://www.facebook.com/p/The-Habesha-Garden-Restaurant-100063880364326/","source":"https://www.yelp.com/biz/the-habesha-garden-columbus","secondSource":"https://www.ubereats.com/store/the-habesha-garden-restaurant-4520-josephus-lane/p3YKoHd4U72-TqPStgZOvg","status":"needs-review","verifiedDate":"2026-09-28","publicNote":"Online ordering listings show this restaurant as closed since July 2026. Call ahead to confirm it is open.","notes":"Uber Eats: 'Closed on Uber Eats as of Jul 16, 2026'. Yelp updated Jun 2026. Possible closure; do not mark closed without a second source."},
  {"id":"oh-columbus-ebenezer-ethiopian-evangelical-church","name":"Ebenezer Ethiopian Evangelical Church","altNames":["Ebenezer Ethiopian Evangelical Lutheran Church"],"category":"Church","subcategory":"Lutheran (LCMS)","denomination":"Protestant","address":"700 Bernhard Rd","city":"Whitehall","state":"Ohio","zip":"43213","phone":"(614) 377-8350","website":"https://ebenezereec.com/","source":"https://ebenezereec.com/","secondSource":"https://locator.lcms.org/church/C/1001408","status":"verified","verifiedDate":"2026-09-28","notes":"Official site: 700 Bernhard Rd, Whitehall; Sundays 10am. LCMS locator gives phone (614) 377-8350.","metro":"Columbus"},
  {"id":"oh-columbus-ethiopian-emmanuel-united-church-of-christ","name":"Ethiopian Emmanuel United Church of Christ","altNames":["Ethiopian Emmanuel United Church of Columbus"],"category":"Church","denomination":"Protestant","address":"1055 McNaughten Rd","city":"Columbus","state":"Ohio","phone":"(614) 843-5975","social":"https://www.facebook.com/p/Ethiopian-Emmanuel-United-Church-of-Columbus-100067210424028/","source":"https://www.facebook.com/p/Ethiopian-Emmanuel-United-Church-of-Columbus-100067210424028/","secondSource":"https://www.youtube.com/@eucc1055","status":"community","verifiedDate":"2026-09-28","notes":"Facebook page and YouTube channel (@eucc1055) confirm the congregation; street address and phone not confirmed from an official page."},
  {"id":"oh-pataskala-peniel-ethiopian-evangelical-church","name":"Peniel Ethiopian Evangelical Church","category":"Church","denomination":"Protestant","address":"5457 York Rd SW","city":"Pataskala","state":"Ohio","phone":"(614) 322-0085","social":"https://www.facebook.com/peeccolumbus/","source":"https://www.waze.com/live-map/directions/us/oh/pataskala/peniel-ethiopian-evangelical-church?to=place.ChIJdVn7FONjOIgRThO72N34iuU","secondSource":"https://www.guidestar.org/profile/31-1775265","status":"needs-review","verifiedDate":"2026-09-28","publicNote":"Listed at 5457 York Rd SW, Pataskala; an older record shows 6191 Taylor Rd, Blacklick. Confirm before visiting.","notes":"Map listing: 5457 York Rd SW Pataskala. IRS/Yelp: 6191 Taylor Rd Blacklick 43004. Phone (614) 322-0085 from v1 data, unconfirmed.","metro":"Columbus"},
  {"id":"oh-columbus-debre-selam-kidus-gebriel","name":"Debre Selam Kidus Gebriel","altNames":["Debre Selam Kidus Gebriel Ethiopian Orthodox Tewahedo Church"],"category":"Church","denomination":"Orthodox","address":"1049 E Broad St","city":"Columbus","state":"Ohio","zip":"43205","website":"https://debreselamkidusgabriel.com/","source":"https://debreselamkidusgabriel.com/","secondSource":"https://www.guidestar.org/profile/02-0802157","status":"verified","verifiedDate":"2026-09-28","notes":"Official website and IRS record agree on 1049 E Broad St 43205."},
  {"id":"oh-columbus-saint-michael-ethiopian-orthodox-tewahedo-church","name":"Saint Michael Ethiopian Orthodox Tewahedo Church","altNames":["Debre Genet Saint Michael and Abune Gebre Menfes Kidus Ethiopian Orthodox Tewahedo Church","St. Michael Ethiopian Orthodox Church"],"category":"Church","denomination":"Orthodox","address":"3425 Refugee Rd","city":"Columbus","state":"Ohio","zip":"43232","website":"https://www.columbusmichael.org/","source":"https://www.columbusmichael.org/","secondSource":"https://www.waze.com/live-map/directions/us/oh/columbus/saint-michael-ethiopian-orthodox-tewahedo-church-in-columbus-ohio?to=place.ChIJCWgcUVh9OIgR_MUizTR59wQ","status":"verified","verifiedDate":"2026-09-28","notes":"Official website confirms full name, EOTC tradition and 3425 Refugee Rd."},
  {"id":"oh-columbus-debre-medihanit-medhanealem-ethiopian-orthodox-tewahedo-church","name":"Debre Medihanit Medhanealem Ethiopian Orthodox Tewahedo Church","altNames":["Debre Medhanit Medhane Alem","Ethiopian Orthodox Tewahdo Church Columbus Ohio Medhannealem"],"category":"Church","denomination":"Orthodox","address":"4295 E Broad St","city":"Columbus","state":"Ohio","zip":"43213","source":"https://www.guidestar.org/profile/31-1405449","secondSource":"https://www.yelp.com/biz/ethiopian-orthodox-tewahedo-church-debre-medhanit-medhane-alem-c-columbus","status":"community","verifiedDate":"2026-09-28","publicNote":"Two addresses appear online (4295 E Broad St and 610 Neil Ave). Please call or check the church's announcements before visiting.","notes":"IRS/GuideStar: 4295 E Broad St 43213. Yelp: 610 Neil Ave. No official website found. Downgraded from verified until the service location is confirmed."},
  {"id":"oh-columbus-etss-tewahedo-social-services","name":"ETSS Tewahedo Social Services","altNames":["Ethiopian Tewahedo Social Services"],"category":"Community","subcategory":"Immigrant and refugee social services","address":"4300 E Broad St Ste D","city":"Columbus","state":"Ohio","zip":"43213","phone":"(614) 252-5362","website":"https://www.ethiotss.org/","source":"https://adamhfranklin.org/provider/etss-tewahedo-social-services/","secondSource":"https://www.ethiotss.org/","status":"verified","verifiedDate":"2026-09-28","notes":"ADAMH Board of Franklin County lists 4300 E Broad St Suite D; United Way listing shows older address 1060 Mt Vernon Ave."},
  {"id":"ny-new-york-queen-of-sheba","name":"Queen of Sheba","category":"Restaurant","address":"650 10th Ave","city":"New York","state":"New York","zip":"10036","source":"https://w42st.com/post/after-25-years-of-ethiopian-fare-queen-of-sheba-prepares-to-say-goodbye-to-hells-kitchen/","secondSource":"https://www.yelp.com/biz/queen-of-sheba-new-york","status":"closed","verifiedDate":"2026-09-28","notes":"CLOSED: closure after 25 years reported by W42ST and Ethiopia Observer (Apr 2025); Yelp marks CLOSED (Sep 2026). Restaurant website still online but stale. Hidden from site.","metro":"New York City"},
  {"id":"ny-new-york-haile","name":"Haile Bistro","altNames":["Haile Ethiopian Cuisine","Haile"],"category":"Restaurant","subcategory":"Ethiopian restaurant","address":"182 Avenue B #1","city":"New York","state":"New York","zip":"10009","source":"https://www.yelp.com/biz/haile-bistro-new-york","secondSource":"https://hailebistro.netwaiter.com/","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","keywords":["Manhattan","East Village"],"metro":"New York City"},
  {"id":"ny-new-york-benyam","name":"Benyam Ethiopian Cuisine","altNames":["Benyam"],"category":"Restaurant","subcategory":"Ethiopian restaurant","address":"2795 Frederick Douglass Blvd","city":"New York","state":"New York","zip":"10039","phone":"(212) 510-7353","website":"https://www.benyamcuisine.com/","source":"https://www.benyamcuisine.com/contact/","secondSource":"https://www.yelp.com/biz/benyam-cuisine-new-york","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","keywords":["Harlem","Manhattan"],"metro":"New York City"},
  {"id":"ny-sunnyside-makina-cafe","name":"Makina Cafe","category":"Restaurant","subcategory":"Eritrean-Ethiopian restaurant","address":"46-11 Skillman Ave","city":"Sunnyside","state":"New York","zip":"11104","website":"https://www.makinacafenyc.com/","source":"https://qns.com/2026/04/makina-cafe-ethiopian-sunnyside/","secondSource":"https://www.yelp.com/biz/makina-cafe-sunnyside","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","keywords":["Queens"],"metro":"New York City"},
  {"id":"ny-brooklyn-bunna-cafe","name":"Bunna Cafe","category":"Restaurant","subcategory":"Plant-based Ethiopian restaurant","address":"1084 Flushing Ave","city":"Brooklyn","state":"New York","zip":"11237","website":"https://www.bunnaethiopia.net/","source":"https://www.bunnaethiopia.net/","secondSource":"https://www.yelp.com/biz/bunna-cafe-brooklyn","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","metro":"New York City"},
  {"id":"ny-brooklyn-ras-plant-based","name":"RAS Plant Based","category":"Restaurant","subcategory":"Plant-based Ethiopian restaurant","address":"739 Franklin Ave","city":"Brooklyn","state":"New York","zip":"11238","website":"https://www.rasplantbased.com/","source":"https://www.rasplantbased.com/location/ras-planted-based-brooklyn/","secondSource":"https://www.yelp.com/biz/ras-plant-based-brooklyn","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded.","metro":"New York City"},
  {"id":"nj-south-orange-walia-ethiopian-restaurant","name":"Walia Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"11 Village Plaza","city":"South Orange","state":"New Jersey","zip":"07079","phone":"(973) 762-2186","website":"https://waliarestaurant.com/","source":"https://waliarestaurant.com/contact/","secondSource":"https://www.yelp.com/biz/walia-ethiopian-restaurant-south-orange-2","status":"verified","verifiedDate":"2026-09-28","notes":"Migrated from v1 data (status was 'verified'); v1 had no source or date recorded."},
  {"id":"nj-newark-bisrate-gebriel-ethiopian-orthodox-tewahedo-church","name":"Bisrate Gebriel Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"1046 S Orange Ave","city":"Newark","state":"New Jersey","zip":"07106","social":"https://www.facebook.com/BisrateGebrielEOTCNJ/","source":"https://www.waze.com/live-map/directions/us/nj/newark/bisrate-gebriel-ethiopian-orthodox-tewahedo-church?to=place.ChIJgTBycKasw4kRUnG4bt7rdnk","secondSource":"https://habeshalink.com/listings/bisrate-gebriel-ethiopian-orthodox-tewahedo-church/","status":"community","verifiedDate":"2026-09-28","notes":"Map listing and HabeshaLink directory; no official website found. Downgraded from verified."},
  {"id":"dc-washington-chercher-columbia-heights","name":"Chercher Ethiopian Restaurant (Columbia Heights)","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"3608 14th St NW","city":"Washington","state":"District of Columbia","zip":"20010","phone":"(202) 222-0433","website":"https://chercherrestaurant.com/","source":"https://chercherrestaurant.com/","status":"verified","verifiedDate":"2026-09-28","notes":"Location listed on official Chercher site."},
  {"id":"md-bethesda-chercher-bethesda","name":"Chercher Ethiopian Restaurant (Bethesda)","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"4921 Bethesda Ave","city":"Bethesda","state":"Maryland","zip":"20814","phone":"(301) 652-6500","website":"https://chercherrestaurant.com/","source":"https://chercherrestaurant.com/","status":"verified","verifiedDate":"2026-09-28","notes":"Location listed on official Chercher site."},
  {"id":"dc-washington-elfegne","name":"Elfegne Ethiopian Cuisine","altNames":["Elfegne"],"category":"Restaurant","subcategory":"Ethiopian restaurant","address":"2420 18th St NW","city":"Washington","state":"District of Columbia","zip":"20009","phone":"(202) 667-4700","website":"https://www.elfegnedc.com/","source":"https://www.elfegnedc.com/about-us/","secondSource":"https://www.theinfatuation.com/washington-dc/guides/best-ethiopian-restaurants","status":"community","verifiedDate":"2026-09-28","publicNote":"This location has changed owners or concepts recently. Confirm hours before visiting.","notes":"Official site shows normal hours; Infatuation guide (updated Jul 2026) lists it; but Yelp shows the earlier 'Elfegne' page CLOSED (Jun 2026) and a new 'Elfegne Ethiopian Cuisine' page (Aug 2026) at the same address. Recheck in 3 months."},
  {"id":"dc-washington-das-ethiopian","name":"Das Ethiopian Cuisine","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"1201 28th St NW","city":"Washington","state":"District of Columbia","zip":"20007","phone":"(202) 333-4710","website":"https://dasethiopian.com/","source":"https://dasethiopian.com/contact-us/","secondSource":"https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/das","status":"verified","verifiedDate":"2026-09-28","keywords":["Georgetown"]},
  {"id":"dc-washington-doro-soul-food","name":"Doro Soul Food","category":"Restaurant","subcategory":"Ethiopian-Southern fried chicken (Chef Elias Taddesse)","address":"1819 7th St NW","city":"Washington","state":"District of Columbia","zip":"20001","website":"https://www.dorosoulfood.com/","source":"https://midcitydcnews.com/2023/05/19/carryout-with-an-ethiopian-twist-at-doro-soul-food/","secondSource":"https://www.theinfatuation.com/washington-dc/guides/best-ethiopian-restaurants","status":"verified","verifiedDate":"2026-09-28","keywords":["Shaw"]},
  {"id":"dc-washington-letena","name":"Letena Ethiopian Restaurant","altNames":["Letena"],"category":"Restaurant","subcategory":"Ethiopian restaurant","address":"3100 14th St NW, Suite 121","city":"Washington","state":"District of Columbia","zip":"20010","website":"https://order.toasttab.com/online/letenadc","source":"https://www.yelp.com/biz/letena-ethiopian-restaurant-washington","secondSource":"https://www.theinfatuation.com/washington-dc/guides/best-ethiopian-restaurants","status":"verified","verifiedDate":"2026-09-28","keywords":["Columbia Heights"]},
  {"id":"dc-washington-family-ethiopian","name":"Family Ethiopian Restaurant","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"1414 9th St NW","city":"Washington","state":"District of Columbia","zip":"20001","phone":"(202) 629-2950","website":"https://familyethiopianrestaurant.com/","source":"https://familyethiopianrestaurant.com/","secondSource":"https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/family-ethiopian","status":"verified","verifiedDate":"2026-09-28","keywords":["Shaw"]},
  {"id":"dc-washington-ethiopic","name":"Ethiopic Restaurant","altNames":["Ethiopic"],"category":"Restaurant","subcategory":"Ethiopian restaurant","address":"401 H St NE","city":"Washington","state":"District of Columbia","zip":"20002","phone":"(202) 675-2066","website":"https://www.ethiopicrestaurant.com/","source":"https://www.ethiopicrestaurant.com/contact/","secondSource":"https://www.yelp.com/biz/ethiopic-washington","status":"verified","verifiedDate":"2026-09-28","keywords":["H Street"]},
  {"id":"dc-washington-dukem","name":"Dukem Ethiopian Restaurant","altNames":["Dukem"],"category":"Restaurant","subcategory":"Ethiopian restaurant","address":"1114-1118 U St NW","city":"Washington","state":"District of Columbia","zip":"20009","phone":"(202) 667-8735","website":"https://dukemrestaurant.com/US/","source":"https://dukemrestaurant.com/US/","secondSource":"https://www.yelp.com/biz/dukem-ethiopian-restaurant-washington","status":"verified","verifiedDate":"2026-09-28","keywords":["U Street","Little Ethiopia"]},
  {"id":"dc-washington-heat-da-spot","name":"Heat Da Spot Cafe","category":"Restaurant","subcategory":"Cafe serving Ethiopian breakfast and coffee","address":"3213 Georgia Ave NW","city":"Washington","state":"District of Columbia","zip":"20010","website":"https://heatdaspotdc.com/","source":"https://intentionalist.com/b/heat-da-spot-cafe/","secondSource":"https://www.theinfatuation.com/washington-dc/guides/best-ethiopian-restaurants","status":"community","verifiedDate":"2026-09-28","notes":"Included in Infatuation's best Ethiopian restaurants guide; menu features Ethiopian breakfast combo. Owners' background not stated; listed for Ethiopian-focused menu only."},
  {"id":"md-hyattsville-selam-market-carryout","name":"Selam Market & Carryout","category":"Grocery","subcategory":"Ethiopian market and carryout","address":"6521 Riggs Rd","city":"Hyattsville","state":"Maryland","zip":"20782","phone":"(240) 770-3971","website":"https://www.selammarketcarryout.com/","source":"https://www.selammarketcarryout.com/","secondSource":"https://www.doordash.com/store/selam-market-hyattsville-804353/","status":"community","verifiedDate":"2026-09-28","notes":"Official site gives address and phone. Ethiopian focus inferred from Habesha-market listings; confirm menu/products on next check. Not confirmed to be the same business as the old Selam International Market (DC)."},
  {"id":"va-falls-church-skyline-cafe","name":"Skyline Cafe Ethiopian Cuisine","category":"Restaurant","subcategory":"Ethiopian restaurant","address":"3821 S George Mason Dr","city":"Falls Church","state":"Virginia","zip":"22041","phone":"(703) 820-0240","source":"https://skylinecafe3.netwaiter.com/","secondSource":"https://www.yelp.com/biz/skyline-cafe-falls-church-3","status":"verified","verifiedDate":"2026-09-28","keywords":["Bailey's Crossroads"]},
  {"id":"va-falls-church-abay-market","name":"Abay Market","altNames":["Abay Ethiopian Market"],"category":"Grocery","subcategory":"Ethiopian market and deli","address":"3811 S George Mason Dr, Suite A","city":"Falls Church","state":"Virginia","zip":"22041","source":"https://www.yelp.com/biz/abay-market-falls-church","secondSource":"https://habeshalink.com/ethiopian-markets-and-shops-in-dc-md-and-va/","status":"verified","verifiedDate":"2026-09-28","notes":"Yelp (Ethiopian, updated Jul 2026) and 2013 community list agree on address."},
  {"id":"va-falls-church-kera-ethiopian-restaurant-market","name":"Kera Ethiopian Restaurant and Market","category":"Grocery","subcategory":"Ethiopian market and restaurant","address":"3823 S George Mason Dr","city":"Falls Church","state":"Virginia","zip":"22041","source":"https://www.yelp.com/biz/kera-ethiopian-restaurant-and-market-fall-church","status":"community","verifiedDate":"2026-09-28","notes":"Single source (Yelp, updated Jun 2026)."},
  {"id":"md-temple-hills-debre-genet-medhane-alem","name":"Debre Genet Medhane Alem Ethiopian Orthodox Tewahido Church","category":"Church","denomination":"Orthodox","address":"4401 Old Branch Ave","city":"Temple Hills","state":"Maryland","zip":"20748","phone":"(301) 899-6090","website":"https://dgmedhanealem.org/","source":"https://dgmedhanealem.org/contact/","secondSource":"https://www.guidestar.org/profile/52-1193241","status":"verified","verifiedDate":"2026-09-28"},
  {"id":"dc-washington-debre-hail-kedus-gabriel","name":"Debre Hail Kedus Gabriel Ethiopian Orthodox Tewahedo Cathedral","altNames":["St. Gabriel's DC"],"category":"Church","denomination":"Orthodox","address":"2601 Evarts St NE","city":"Washington","state":"District of Columbia","zip":"20018","phone":"(202) 269-0146","website":"https://dcgabriel.org/","social":"https://www.facebook.com/dcgabrielchurch/","source":"https://dcgabriel.org/","secondSource":"https://www.guidestar.org/profile/27-1223004","status":"verified","verifiedDate":"2026-09-28"},
  {"id":"va-sterling-debre-haile-kidus-raguael","name":"Debre Haile Kidus Raguael Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"1001 Ruritan Cir","city":"Sterling","state":"Virginia","zip":"20164","phone":"(703) 938-4880","website":"https://dhkidusraguel.org/","social":"https://www.facebook.com/DHKR.EOTC/","source":"https://dhkidusraguel.org/about","status":"verified","verifiedDate":"2026-09-28"},
  {"id":"va-alexandria-hamere-noah-kidane-mehret","name":"Hamere Noah Kidane Mehret Ethiopian Orthodox Tewahedo Church","category":"Church","denomination":"Orthodox","address":"75 S Bragg St","city":"Alexandria","state":"Virginia","zip":"22312","social":"https://www.facebook.com/KMEOTC/","source":"https://www.waze.com/live-map/directions/hamere-noah-kidane-mehret-church-s-bragg-st-75-alexandria?to=place.w.185401732.1853755178.3334525","secondSource":"https://opencorpdata.com/us-va/07177447","status":"verified","verifiedDate":"2026-09-28","notes":"Map listing and Virginia corporate record agree on 75 S Bragg St."},
  {"id":"md-silver-spring-four-corners-eec","name":"Four Corners Ethiopian Evangelical Church","category":"Church","subcategory":"Evangelical (Pentecostal)","denomination":"Protestant","address":"33 University Blvd E","city":"Silver Spring","state":"Maryland","zip":"20901","phone":"(610) 506-4619","website":"https://www.4cornerseec.org/","source":"https://www.4cornerseec.org/","secondSource":"https://times12.org/awp-churches/four-corners-ethiopian-evangelical-church/","status":"verified","verifiedDate":"2026-09-28"},
  {"id":"md-forestville-kidane-mehret-ethiopian-catholic","name":"Kidane-Mehret Ge'ez Rite Ethiopian Catholic Church","category":"Church","subcategory":"Ethiopian Catholic (Ge'ez Rite)","denomination":"Catholic","address":"1717 Ritchie Rd","city":"Forestville","state":"Maryland","phone":"(202) 756-2756","website":"https://kidane-mehret.org/","social":"https://www.facebook.com/KidanemehretDC/","source":"https://www.cathstan.org/local/after-41-year-odyssey-ethiopian-catholics-kidane-mehret-parish-finds-a-church-home-holy-spirit-in-forestville","secondSource":"https://adw.org/parishes/kidane-mehret/","status":"verified","verifiedDate":"2026-09-28","notes":"Moved Aug 2025 to former Holy Spirit Church, 1717 Ritchie Rd, Forestville (Catholic Standard). Archdiocese page still lists older address 5001 Eastern Ave NE, Hyattsville.","keywords":["Washington DC"]},
  {"id":"va-arlington-ecdc","name":"Ethiopian Community Development Council (ECDC)","category":"Community","subcategory":"Refugee resettlement and immigrant services nonprofit","address":"901 S Highland St","city":"Arlington","state":"Virginia","zip":"22204","phone":"(703) 685-0510","website":"https://www.ecdcus.org/","source":"https://www.ecdcus.org/contact-us/","secondSource":"https://www.guidestar.org/profile/52-1308986","status":"verified","verifiedDate":"2026-09-28"},
  {"id":"dc-washington-ethiopian-community-center","name":"Ethiopian Community Center, Inc. (ECC)","category":"Community","subcategory":"Social services, referrals and immigrant support","address":"7603 Georgia Ave NW, Suite 100","city":"Washington","state":"District of Columbia","zip":"20012","phone":"(202) 726-0800","website":"https://www.ethiopiancommunitydc.org/","social":"https://www.facebook.com/ethiopiancommunitycenterdc/","source":"https://www.lawhelp.org/dc/resource/ethiopian-community-center-inc","secondSource":"https://takomaparkmd.gov/m/newsflash/Home/Detail/343","status":"community","verifiedDate":"2026-09-28","notes":"Organization is active (Takoma Park city news on 46 years of service). Office address from LawHelp DC may be outdated; a Maryland office opened at 8120 Fenton St, Silver Spring in 2014. Confirm current office."},
  {"id":"md-silver-spring-mulu-law","name":"Mulu Law","category":"Professional","subcategory":"Immigration, family and business attorney","address":"8403 Colesville Rd, Suite 400","city":"Silver Spring","state":"Maryland","zip":"20910","phone":"(877) 685-8529","website":"https://www.mululawfirm.com/","source":"https://www.mululawfirm.com/","status":"community","verifiedDate":"2026-09-28","notes":"Firm website describes attorney Mulualem Adgeh as an Ethiopian lawyer with offices in Minneapolis and Silver Spring. Bar admission not yet checked against a licensing database; verify before marking verified."},
  {"id":"md-silver-spring-konjo-hair-salon","name":"Konjo Hair Salon","category":"Beauty","subcategory":"Hair salon","address":"12713 Old Columbia Pike","city":"Silver Spring","state":"Maryland","zip":"20904","social":"https://www.facebook.com/konjohairsalon/","source":"https://www.yelp.com/biz/konjo-hair-salon-silver-spring","secondSource":"https://habeshadeals.com/listing/konjo-hair-salon/","status":"community","verifiedDate":"2026-09-28","notes":"Listed in Habesha directories (HabeshaLink, Habesha Deals). HabeshaLink address (11226 Triangle Ln) is outdated; Yelp (May 2026) address used. Ethiopian ownership not stated on its own pages."},
  {"id":"md-silver-spring-kedus-hair-salon","name":"Kedus Hair Salon & Braiding","category":"Beauty","subcategory":"Hair salon and braiding","address":"7851 Eastern Ave","city":"Silver Spring","state":"Maryland","social":"https://www.facebook.com/kedussalonmd/","source":"https://www.yelp.com/biz/kedus-hair-salon-and-braiding-silver-spring-6","secondSource":"https://habeshalink.com/listings/ethiopian-hair-salon-washington-dc/","status":"community","verifiedDate":"2026-09-28","notes":"Listed in HabeshaLink Ethiopian salon directory (older address 8203 Georgia Ave). Yelp (Jun 2026) shows 7851 Eastern Ave. ZIP not confirmed."},
  {"id":"va-falls-church-almaz-diamond-hair-salon","name":"Almaz Diamond Hair Salon","category":"Beauty","subcategory":"Hair salon","address":"3811 S George Mason Dr, Suite B","city":"Falls Church","state":"Virginia","zip":"22041","phone":"(703) 820-6990","website":"https://almazdiamondhairsalon.wordpress.com/","social":"https://www.instagram.com/almazdiamondhairsalon/","source":"https://almazdiamondhairsalon.wordpress.com/about-us/","secondSource":"https://habeshalink.com/listings/ethiopian-hair-salon-washington-dc/","status":"community","verifiedDate":"2026-09-28","notes":"Listed in HabeshaLink Ethiopian salon directory (with an incorrect Silver Spring address). Salon's own site gives Falls Church address; it does not state Ethiopian ownership."}
];

// Housing posts: see README (Housing). Never include a private street address.
window.HABESHA_HOUSING = [];

window.HABESHA_STATUS_LABELS = {
 "verified": {
  "en": "Verified",
  "am": "የተረጋገጠ"
 },
 "community": {
  "en": "Community listed",
  "am": "በማህበረሰብ የተዘረዘረ"
 },
 "needs-review": {
  "en": "Needs verification",
  "am": "ማረጋገጫ ያስፈልገዋል"
 },
 "temporarily-closed": {
  "en": "Temporarily closed",
  "am": "ለጊዜው ተዘግቷል"
 },
 "closed": {
  "en": "Closed",
  "am": "ተዘግቷል"
 },
 "duplicate": {
  "en": "Duplicate",
  "am": "የተደገመ"
 }
};
