// Habesha Hub community directory data
// Keep listings here so the directory can grow without editing page layout.
// status: "verified" = independently reviewed; "community" = submitted/listed; "needs-review" = needs confirmation.
window.HABESHA_LISTINGS = [
  {name:"Habesha Market",category:"Grocery",city:"Columbus",state:"Ohio",address:"1391 S Hamilton Rd, Columbus, OH",status:"community"},
  {name:"Addis Ababa Grocery",category:"Grocery",city:"Columbus",state:"Ohio",address:"Columbus, OH",status:"needs-review"},
  {name:"Dire Dawa Grocery Store",category:"Grocery",city:"Columbus",state:"Ohio",address:"Columbus, OH",status:"needs-review"},
  {name:"Lalibela Grocery",category:"Grocery",city:"Columbus",state:"Ohio",address:"Columbus, OH",status:"needs-review"},
  {name:"St. Michael Ethiopian Orthodox Church",category:"Church",denomination:"Orthodox",city:"Columbus",state:"Ohio",address:"Columbus, OH",status:"community"},
  {name:"Debre Medhanit Medhane Alem",category:"Church",denomination:"Orthodox",city:"Columbus",state:"Ohio",address:"610 Neil Ave, Columbus, OH",status:"community"},
  {name:"Kidest Sehalte Mehret & St. Urael",category:"Church",denomination:"Orthodox",city:"Columbus",state:"Ohio",address:"Columbus, OH",status:"community"},
  {name:"Selam International Market",category:"Grocery",city:"Washington",state:"District of Columbia",address:"Washington, DC",status:"needs-review"},
  {name:"Merkato Ethiopian Market",category:"Grocery",city:"Springfield",state:"Virginia",address:"Springfield, VA",status:"needs-review"},
  {name:"Tana Ethiopian Market",category:"Grocery",city:"Silver Spring",state:"Maryland",address:"Silver Spring, MD",status:"needs-review"},
  {name:"Skyline International Market",category:"Grocery",city:"Falls Church",state:"Virginia",address:"Falls Church, VA",status:"needs-review"},
  {name:"Chercher Ethiopian Restaurant & Mart",category:"Restaurant",city:"Washington",state:"District of Columbia",address:"1334 9th St NW, Washington, DC 20001",status:"verified"},
  {name:"Habesha Market Carry Out & Restaurant",category:"Restaurant",city:"Washington",state:"District of Columbia",address:"1919 9th St NW, Washington, DC 20001",status:"verified"},
  {name:"Shewa Ethiopian Restaurant",category:"Restaurant",city:"Washington",state:"District of Columbia",address:"1824 Benning Rd NE, Washington, DC 20002",status:"verified"},
  {name:"Intoto Ethiopian Restaurant and Market",category:"Grocery",city:"Washington",state:"District of Columbia",address:"6406 Georgia Ave NW, Washington, DC 20012",status:"verified"},
  {name:"Debre Selam Kidist Mariam Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Washington",state:"District of Columbia",address:"1350 Buchanan St NW, Washington, DC 20011",status:"verified"},
  {name:"Debre Meheret Kedus Michael Ethiopian Orthodox Cathedral",category:"Church",denomination:"Orthodox",city:"Washington",state:"District of Columbia",address:"3010 Earl Pl NE, Washington, DC 20018",status:"verified"},
  {name:"International Ethiopian Evangelical Church",category:"Church",denomination:"Protestant",city:"Washington",state:"District of Columbia",address:"7930 Eastern Ave NW, Washington, DC 20012",status:"verified"},
  {name:"ADOT International Market",category:"Grocery",city:"Mount Rainier",state:"Maryland",address:"3111 Chillum Rd, Mount Rainier, MD 20712",status:"verified"},
  {name:"Beteseb Restaurant",category:"Restaurant",city:"Silver Spring",state:"Maryland",address:"8201 Georgia Ave, Silver Spring, MD 20910",status:"verified"},
  {name:"Abyssinia Ethiopian Restaurant",category:"Restaurant",city:"Silver Spring",state:"Maryland",address:"8221 Georgia Ave, Silver Spring, MD 20910",status:"verified"},
  {name:"Sheger Spring Cafe",category:"Restaurant",city:"Silver Spring",state:"Maryland",address:"900 Silver Spring Ave, Silver Spring, MD 20910",status:"verified"},
  {name:"Langano Ethiopian Restaurant",category:"Restaurant",city:"Silver Spring",state:"Maryland",address:"8305 Georgia Ave, Silver Spring, MD 20910",status:"verified"},
  {name:"Woder Ethiopian Carryout & Market",category:"Grocery",city:"Silver Spring",state:"Maryland",address:"7845 Eastern Ave, Silver Spring, MD 20910",status:"verified"},
  {name:"Zema Market",category:"Grocery",city:"Alexandria",state:"Virginia",address:"8714 Richmond Hwy, Alexandria, VA 22309",status:"verified"},
  {name:"ZeMeda Market and Restaurant",category:"Restaurant",city:"Alexandria",state:"Virginia",address:"512 B South Van Dorn St, Alexandria, VA 22304",status:"verified"},
  {name:"Time Ethiopian Cafe and Market",category:"Restaurant",city:"Lincolnia",state:"Virginia",address:"4701 N Chambliss St, Lincolnia, VA 22312",status:"verified"},
  {name:"Regal Abyssinia",category:"Restaurant",city:"Falls Church",state:"Virginia",address:"3821 S George Mason Dr, Falls Church, VA 22041",status:"verified"},
  {name:"Dama Restaurant and Pastry",category:"Restaurant",city:"Arlington",state:"Virginia",address:"1505 Columbia Pike, Arlington, VA 22204",status:"verified"},
  {name:"Hawwi Ethiopian Restaurant",category:"Restaurant",city:"Alexandria",state:"Virginia",address:"1125 Queen St, Alexandria, VA 22314",status:"verified"},
  {name:"Gospel Believers Ethiopian Church",category:"Church",denomination:"Protestant",city:"Sterling",state:"Virginia",address:"1402 Shepard Dr, Sterling, VA 20164",status:"verified"},
  {name:"Virginia Evangelical Lutheran Church Mekane Yesus",category:"Church",denomination:"Protestant",city:"Annandale",state:"Virginia",address:"3901 Gallows Rd, Annandale, VA 22003",status:"verified"},
  {name:"Embilta Cafe & Restaurant",category:"Restaurant",city:"Atlanta",state:"Georgia",address:"2100 Cheshire Bridge Rd NE, Atlanta, GA 30324",status:"verified"},
  {name:"Ethiopian Evangelical Church Atlanta",category:"Church",denomination:"Protestant",city:"Stone Mountain",state:"Georgia",address:"4550 Greer Cir, Stone Mountain, GA 30083",status:"verified"},
  {name:"Ebenezer Ethiopian Evangelical Church Atlanta",category:"Church",denomination:"Protestant",city:"Stone Mountain",state:"Georgia",address:"4528 Rockbridge Rd SW, Stone Mountain, GA 30083",status:"verified"},
  {name:"Mekane Hiwot Abune Gebre Menfes Kidus EOTC",category:"Church",denomination:"Orthodox",city:"Atlanta",state:"Georgia",address:"Atlanta, GA",status:"verified"},
  {name:"Desta Ethiopian Restaurant",category:"Restaurant",city:"Dallas",state:"Texas",address:"12101 Greenville Ave #105, Dallas, TX 75243",status:"verified"},
  {name:"Abyssinia Grocery and Ethiopian Food",category:"Grocery",city:"Dallas",state:"Texas",address:"9191 Forest Ln #1A, Dallas, TX 75243",status:"verified"},
  {name:"Awudamet Market",category:"Grocery",city:"Dallas",state:"Texas",address:"9751 Walnut St #102, Dallas, TX 75243",status:"verified"},
  {name:"Debre Mehret St. Michael Ethiopian Orthodox Tewahedo Cathedral",category:"Church",denomination:"Orthodox",city:"Garland",state:"Texas",address:"1106 N Jupiter Rd, Garland, TX 75042",status:"verified"},
  {name:"Ethiopian Evangelical Believers Church",category:"Church",denomination:"Protestant",city:"Garland",state:"Texas",address:"3001 Saturn Rd, Garland, TX 75041",status:"verified"},
  {name:"Blue Nile",category:"Restaurant",city:"Houston",state:"Texas",address:"3030 Audley St, Houston, TX 77098",status:"verified"},
  {name:"Bahel Ethiopian Mart and Dining",category:"Restaurant",city:"Houston",state:"Texas",address:"6509 Chimney Rock Rd, Houston, TX 77081",status:"verified"},
  {name:"Selam Ethio-Eritrea Specialty Store",category:"Grocery",city:"Houston",state:"Texas",address:"5701 Bellaire Blvd D, Houston, TX 77081",status:"verified"},
  {name:"Debre Selam Medhane Alem Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Houston",state:"Texas",address:"11614 Canemont St, Houston, TX 77035",status:"verified"},
  {name:"Holy Trinity and Saint Mary Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Houston",state:"Texas",address:"8231 McGee Ln, Houston, TX 77071",status:"verified"},
  {name:"Ethiopian Community Organization in Houston",category:"Community",city:"Houston",state:"Texas",address:"6671 Southwest Fwy #439, Houston, TX 77074",status:"verified"},
  {name:"Delish Ethiopian Cuisine",category:"Restaurant",city:"Seattle",state:"Washington",address:"5701 Rainier Ave S, Seattle, WA 98118",status:"verified"},
  {name:"Jebena Cafe",category:"Restaurant",city:"Seattle",state:"Washington",address:"1510 NE 117th St, Seattle, WA 98125",status:"verified"},
  {name:"Nazareth Market",category:"Grocery",city:"Seattle",state:"Washington",address:"5418 Martin Luther King Jr Way S, Seattle, WA 98118",status:"verified"},
  {name:"East African Imports & Restaurant",category:"Grocery",city:"Seattle",state:"Washington",address:"306 23rd Ave S #104, Seattle, WA 98144",status:"verified"},
  {name:"Addis Market Seattle",category:"Grocery",city:"Seattle",state:"Washington",address:"13500 Aurora Ave N #B, Seattle, WA 98133",status:"verified"},
  {name:"Ethiopian Community in Seattle",category:"Community",city:"Seattle",state:"Washington",address:"8323 Rainier Ave S Suite A, Seattle, WA 98118",status:"verified"},
  {name:"Mesob Ethiopian Restaurant",category:"Restaurant",city:"Minneapolis",state:"Minnesota",address:"3915 Hiawatha Ave, Minneapolis, MN 55406",status:"verified"},
  {name:"The Red Sea Ethiopian Restaurant",category:"Restaurant",city:"Minneapolis",state:"Minnesota",address:"320 Cedar Ave S, Minneapolis, MN 55454",status:"verified"},
  {name:"KELA Market",category:"Grocery",city:"Minneapolis",state:"Minnesota",address:"4020 Minnehaha Ave, Minneapolis, MN 55406",status:"verified"},
  {name:"Shabelle Ethiopian Grocery",category:"Grocery",city:"Minneapolis",state:"Minnesota",address:"2325 E Franklin Ave, Minneapolis, MN 55406",status:"verified"},
  {name:"Re'ese Adbarat Tserha Aryam Kidist Selassie Ethiopian Orthodox Tewahedo Cathedral",category:"Church",denomination:"Orthodox",city:"Minneapolis",state:"Minnesota",address:"2601 Minnehaha Ave, Minneapolis, MN 55406",status:"verified"},
  {name:"Debre Selam Medhanealem Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Minneapolis",state:"Minnesota",address:"2629 30th Ave S, Minneapolis, MN 55406",status:"verified"},
  {name:"Eatopia: Eat Ethiopian",category:"Restaurant",city:"Aurora",state:"Colorado",address:"1030 Havana St B, Aurora, CO 80010",status:"verified"},
  {name:"Gursha Ethiopian Restaurant",category:"Restaurant",city:"Aurora",state:"Colorado",address:"15373 E 6th Ave Unit B, Aurora, CO 80011",status:"verified"},
  {name:"Piassa Retail Store & Restaurant",category:"Grocery",city:"Aurora",state:"Colorado",address:"601 Salida Way Unit B5, Aurora, CO 80011",status:"verified"},
  {name:"Gihon International Market",category:"Grocery",city:"Aurora",state:"Colorado",address:"16761 E Iliff Ave, Aurora, CO 80013",status:"verified"},
  {name:"Ethiopian Orthodox Tewahedo Debre Selam Medhanealem Church",category:"Church",denomination:"Orthodox",city:"Denver",state:"Colorado",address:"5152 E 17th Ave Pkwy, Denver, CO 80220",status:"verified"},
  {name:"St Mary Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Aurora",state:"Colorado",address:"16250 E Colfax Ave, Aurora, CO 80011",status:"verified"},
  {name:"Messob Ethiopian Restaurant",category:"Restaurant",city:"Los Angeles",state:"California",address:"1041 S Fairfax Ave, Los Angeles, CA 90019",status:"verified"},
  {name:"Rosalind's Ethiopian Restaurant",category:"Restaurant",city:"Los Angeles",state:"California",address:"1044 S Fairfax Ave, Los Angeles, CA 90019",status:"verified"},
  {name:"Buna Ethiopian Restaurant & Market",category:"Grocery",city:"Los Angeles",state:"California",address:"1034 S Fairfax Ave, Los Angeles, CA 90019",status:"verified"},
  {name:"Gojo Ethio Market",category:"Grocery",city:"Los Angeles",state:"California",address:"3417 S La Brea Ave, Los Angeles, CA 90016",status:"verified"},
  {name:"St Mary's Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Los Angeles",state:"California",address:"5505 W Slauson Ave, Los Angeles, CA 90056",status:"verified"},
  {name:"Addis Restaurant",category:"Restaurant",city:"Columbus",state:"Ohio",address:"3750 Cleveland Ave, Columbus, OH 43224",status:"verified"},
  {name:"The Habesha Garden Restaurant",category:"Restaurant",city:"Columbus",state:"Ohio",address:"4520 Josephus Ln, Columbus, OH 43227",status:"verified"},
  {name:"Ebenezer Ethiopian Evangelical Church",category:"Church",denomination:"Protestant",city:"Columbus",state:"Ohio",address:"700 Bernhard Rd, Columbus, OH",phone:"(614) 377-8350",status:"community"},
  {name:"Ethiopian Emmanuel United Church of Christ",category:"Church",denomination:"Protestant",city:"Columbus",state:"Ohio",address:"1055 McNaughten Rd, Columbus, OH",phone:"(614) 843-5975",status:"community"},
  {name:"Peniel Ethiopian Evangelical Church",category:"Church",denomination:"Protestant",city:"Pataskala",state:"Ohio",address:"Pataskala, OH",phone:"(614) 322-0085",status:"community"},
  {name:"Debre Selam Kidus Gebriel",category:"Church",denomination:"Orthodox",city:"Columbus",state:"Ohio",address:"1049 E Broad St, Columbus, OH 43205",status:"community"},
  {name:"Saint Michael Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Columbus",state:"Ohio",address:"3425 Refugee Rd, Columbus, OH 43232",status:"verified"},
  {name:"Debre Medihanit Medhanealem Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Columbus",state:"Ohio",address:"4295 E Broad St, Columbus, OH 43213",status:"verified"},
  {name:"ETSS Tewahedo Social Services",category:"Community",city:"Columbus",state:"Ohio",address:"4300 E Broad St Ste D, Columbus, OH 43213",status:"verified"},
  {name:"Queen of Sheba",category:"Restaurant",city:"New York",state:"New York",address:"650 10th Ave, New York, NY 10036",status:"verified"},
  {name:"Haile",category:"Restaurant",city:"New York",state:"New York",address:"182 Avenue B #1, New York, NY 10009",status:"verified"},
  {name:"Benyam",category:"Restaurant",city:"New York",state:"New York",address:"2795 Frederick Douglass Blvd, New York, NY 10039",status:"verified"},
  {name:"Makina Cafe",category:"Restaurant",city:"Sunnyside",state:"New York",address:"46-11 Skillman Ave, Sunnyside, NY 11104",status:"verified"},
  {name:"Bunna Cafe",category:"Restaurant",city:"Brooklyn",state:"New York",address:"1084 Flushing Ave, Brooklyn, NY 11237",status:"verified"},
  {name:"RAS Plant Based",category:"Restaurant",city:"Brooklyn",state:"New York",address:"739 Franklin Ave, Brooklyn, NY 11238",status:"verified"},
  {name:"Walia Ethiopian Restaurant",category:"Restaurant",city:"South Orange",state:"New Jersey",address:"11 Village Plaza, South Orange, NJ 07079",status:"verified"},
  {name:"Bisrate Gebriel Ethiopian Orthodox Tewahedo Church",category:"Church",denomination:"Orthodox",city:"Newark",state:"New Jersey",address:"1046 S Orange Ave, Newark, NJ 07106",status:"verified"}
];
window.HABESHA_STATUS_LABELS={
  "verified":"Verified",
  "community":"Community listed",
  "needs-review":"Needs verification"
};