(function(){"use strict";
var q=new URLSearchParams(location.search);
var map={add:"Add a business or organization",church:"Add a church",professional:"Add a professional",housing:"Add housing",correction:"Correct a listing",claim:"Claim a listing",closed:"Report closed or moved",scam:"Report a housing scam or safety issue",remove:"Request removal",event:"Submit an event",contact:"General question or contact"};
var FORM="https://docs.google.com/forms/d/e/1FAIpQLSfk9KdeowBKfEt_6edfqKAgMBkuQ9NnJ3jJ4-2lBHf8joMosA/viewform";
var p=new URLSearchParams();
p.set("usp","pp_url");
var type=map[q.get("type")]||"";
if(type)p.set("entry.2143705137",type);
if(q.get("name"))p.set("entry.1710451381",q.get("name").slice(0,120));
if(q.get("city"))p.set("entry.860530315",q.get("city").slice(0,80));
if(q.get("state"))p.set("entry.447872666",q.get("state").slice(0,80));
if(q.get("id"))p.set("entry.1798896994",q.get("id").slice(0,80));
var target=FORM+"?"+p.toString();
var link=document.getElementById("openPrivateForm");
if(link)link.href=target;
var frame=document.getElementById("privateFormFrame");
if(frame)frame.src=target.replace("/viewform?","/viewform?embedded=true&");
})();